# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

struct WellKnownApi <: SwaggerApi
    client::Swagger.Client
end

function _swaggerinternal_getServiceAccountIssuerOpenIDConfiguration(_api::WellKnownApi; _mediaType=nothing)
    _ctx = Swagger.Ctx(_api.client, "GET", String, "/.well-known/openid-configuration/", ["BearerToken"])
    Swagger.set_header_accept(_ctx, ["application/json"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

"""

get service account issuer OpenID configuration, also known as the 'OIDC discovery doc'
Return: String
"""
function getServiceAccountIssuerOpenIDConfiguration(_api::WellKnownApi; _mediaType=nothing)
    _ctx = _swaggerinternal_getServiceAccountIssuerOpenIDConfiguration(_api; _mediaType=_mediaType)
    Swagger.exec(_ctx)
end

function getServiceAccountIssuerOpenIDConfiguration(_api::WellKnownApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _swaggerinternal_getServiceAccountIssuerOpenIDConfiguration(_api; _mediaType=_mediaType)
    Swagger.exec(_ctx, response_stream)
end

export getServiceAccountIssuerOpenIDConfiguration
