# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

struct KarpenterShV1alpha5Api <: SwaggerApi
    client::Swagger.Client
end

function _swaggerinternal_createKarpenterShV1alpha5Provisioner(_api::KarpenterShV1alpha5Api, body; pretty=nothing, dryRun=nothing, fieldManager=nothing, _mediaType=nothing)
    _ctx = Swagger.Ctx(_api.client, "POST", ShKarpenterV1alpha5Provisioner, "/apis/karpenter.sh/v1alpha5/provisioners", ["BearerToken"], body)
    Swagger.set_param(_ctx.query, "pretty", pretty)  # type String
    Swagger.set_param(_ctx.query, "dryRun", dryRun)  # type String
    Swagger.set_param(_ctx.query, "fieldManager", fieldManager)  # type String
    Swagger.set_header_accept(_ctx, ["application/json", "application/yaml"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", "application/yaml"] : [_mediaType])
    return _ctx
end

"""

create a Provisioner
Param: body::ShKarpenterV1alpha5Provisioner (required)
Param: pretty::String
Param: dryRun::String
Param: fieldManager::String
Return: ShKarpenterV1alpha5Provisioner
"""
function createKarpenterShV1alpha5Provisioner(_api::KarpenterShV1alpha5Api, body; pretty=nothing, dryRun=nothing, fieldManager=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_createKarpenterShV1alpha5Provisioner(_api, body; pretty=pretty, dryRun=dryRun, fieldManager=fieldManager, _mediaType=_mediaType)
    Swagger.exec(_ctx)
end

function createKarpenterShV1alpha5Provisioner(_api::KarpenterShV1alpha5Api, response_stream::Channel, body; pretty=nothing, dryRun=nothing, fieldManager=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_createKarpenterShV1alpha5Provisioner(_api, body; pretty=pretty, dryRun=dryRun, fieldManager=fieldManager, _mediaType=_mediaType)
    Swagger.exec(_ctx, response_stream)
end

function _swaggerinternal_deleteKarpenterShV1alpha5CollectionProvisioner(_api::KarpenterShV1alpha5Api; pretty=nothing, allowWatchBookmarks=nothing, __continue__=nothing, fieldSelector=nothing, labelSelector=nothing, limit=nothing, resourceVersion=nothing, resourceVersionMatch=nothing, timeoutSeconds=nothing, watch=nothing, _mediaType=nothing)
    _ctx = Swagger.Ctx(_api.client, "DELETE", IoK8sApimachineryPkgApisMetaV1StatusV2, "/apis/karpenter.sh/v1alpha5/provisioners", ["BearerToken"])
    Swagger.set_param(_ctx.query, "pretty", pretty)  # type String
    Swagger.set_param(_ctx.query, "allowWatchBookmarks", allowWatchBookmarks)  # type Bool
    Swagger.set_param(_ctx.query, "continue", __continue__)  # type String
    Swagger.set_param(_ctx.query, "fieldSelector", fieldSelector)  # type String
    Swagger.set_param(_ctx.query, "labelSelector", labelSelector)  # type String
    Swagger.set_param(_ctx.query, "limit", limit)  # type Int32
    Swagger.set_param(_ctx.query, "resourceVersion", resourceVersion)  # type String
    Swagger.set_param(_ctx.query, "resourceVersionMatch", resourceVersionMatch)  # type String
    Swagger.set_param(_ctx.query, "timeoutSeconds", timeoutSeconds)  # type Int32
    Swagger.set_param(_ctx.query, "watch", watch)  # type Bool
    Swagger.set_header_accept(_ctx, ["application/json", "application/yaml"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", "application/yaml"] : [_mediaType])
    return _ctx
end

"""

delete collection of Provisioner
Param: pretty::String
Param: allowWatchBookmarks::Bool
Param: __continue__::String
Param: fieldSelector::String
Param: labelSelector::String
Param: limit::Int32
Param: resourceVersion::String
Param: resourceVersionMatch::String
Param: timeoutSeconds::Int32
Param: watch::Bool
Return: IoK8sApimachineryPkgApisMetaV1StatusV2
"""
function deleteKarpenterShV1alpha5CollectionProvisioner(_api::KarpenterShV1alpha5Api; pretty=nothing, allowWatchBookmarks=nothing, __continue__=nothing, fieldSelector=nothing, labelSelector=nothing, limit=nothing, resourceVersion=nothing, resourceVersionMatch=nothing, timeoutSeconds=nothing, watch=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_deleteKarpenterShV1alpha5CollectionProvisioner(_api; pretty=pretty, allowWatchBookmarks=allowWatchBookmarks, __continue__=__continue__, fieldSelector=fieldSelector, labelSelector=labelSelector, limit=limit, resourceVersion=resourceVersion, resourceVersionMatch=resourceVersionMatch, timeoutSeconds=timeoutSeconds, watch=watch, _mediaType=_mediaType)
    Swagger.exec(_ctx)
end

function deleteKarpenterShV1alpha5CollectionProvisioner(_api::KarpenterShV1alpha5Api, response_stream::Channel; pretty=nothing, allowWatchBookmarks=nothing, __continue__=nothing, fieldSelector=nothing, labelSelector=nothing, limit=nothing, resourceVersion=nothing, resourceVersionMatch=nothing, timeoutSeconds=nothing, watch=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_deleteKarpenterShV1alpha5CollectionProvisioner(_api; pretty=pretty, allowWatchBookmarks=allowWatchBookmarks, __continue__=__continue__, fieldSelector=fieldSelector, labelSelector=labelSelector, limit=limit, resourceVersion=resourceVersion, resourceVersionMatch=resourceVersionMatch, timeoutSeconds=timeoutSeconds, watch=watch, _mediaType=_mediaType)
    Swagger.exec(_ctx, response_stream)
end

function _swaggerinternal_deleteKarpenterShV1alpha5Provisioner(_api::KarpenterShV1alpha5Api, name::String; pretty=nothing, body=nothing, dryRun=nothing, gracePeriodSeconds=nothing, orphanDependents=nothing, propagationPolicy=nothing, _mediaType=nothing)
    _ctx = Swagger.Ctx(_api.client, "DELETE", IoK8sApimachineryPkgApisMetaV1StatusV2, "/apis/karpenter.sh/v1alpha5/provisioners/{name}", ["BearerToken"], body)
    Swagger.set_param(_ctx.path, "name", name)  # type String
    Swagger.set_param(_ctx.query, "pretty", pretty)  # type String
    Swagger.set_param(_ctx.query, "dryRun", dryRun)  # type String
    Swagger.set_param(_ctx.query, "gracePeriodSeconds", gracePeriodSeconds)  # type Int32
    Swagger.set_param(_ctx.query, "orphanDependents", orphanDependents)  # type Bool
    Swagger.set_param(_ctx.query, "propagationPolicy", propagationPolicy)  # type String
    Swagger.set_header_accept(_ctx, ["application/json", "application/yaml"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", "application/yaml"] : [_mediaType])
    return _ctx
end

"""

delete a Provisioner
Param: name::String (required)
Param: pretty::String
Param: body::IoK8sApimachineryPkgApisMetaV1DeleteOptionsV2
Param: dryRun::String
Param: gracePeriodSeconds::Int32
Param: orphanDependents::Bool
Param: propagationPolicy::String
Return: IoK8sApimachineryPkgApisMetaV1StatusV2
"""
function deleteKarpenterShV1alpha5Provisioner(_api::KarpenterShV1alpha5Api, name::String; pretty=nothing, body=nothing, dryRun=nothing, gracePeriodSeconds=nothing, orphanDependents=nothing, propagationPolicy=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_deleteKarpenterShV1alpha5Provisioner(_api, name; pretty=pretty, body=body, dryRun=dryRun, gracePeriodSeconds=gracePeriodSeconds, orphanDependents=orphanDependents, propagationPolicy=propagationPolicy, _mediaType=_mediaType)
    Swagger.exec(_ctx)
end

function deleteKarpenterShV1alpha5Provisioner(_api::KarpenterShV1alpha5Api, response_stream::Channel, name::String; pretty=nothing, body=nothing, dryRun=nothing, gracePeriodSeconds=nothing, orphanDependents=nothing, propagationPolicy=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_deleteKarpenterShV1alpha5Provisioner(_api, name; pretty=pretty, body=body, dryRun=dryRun, gracePeriodSeconds=gracePeriodSeconds, orphanDependents=orphanDependents, propagationPolicy=propagationPolicy, _mediaType=_mediaType)
    Swagger.exec(_ctx, response_stream)
end

function _swaggerinternal_listKarpenterShV1alpha5Provisioner(_api::KarpenterShV1alpha5Api; pretty=nothing, allowWatchBookmarks=nothing, __continue__=nothing, fieldSelector=nothing, labelSelector=nothing, limit=nothing, resourceVersion=nothing, resourceVersionMatch=nothing, timeoutSeconds=nothing, watch=nothing, _mediaType=nothing)
    _ctx = Swagger.Ctx(_api.client, "GET", ShKarpenterV1alpha5ProvisionerList, "/apis/karpenter.sh/v1alpha5/provisioners", ["BearerToken"])
    Swagger.set_param(_ctx.query, "pretty", pretty)  # type String
    Swagger.set_param(_ctx.query, "allowWatchBookmarks", allowWatchBookmarks)  # type Bool
    Swagger.set_param(_ctx.query, "continue", __continue__)  # type String
    Swagger.set_param(_ctx.query, "fieldSelector", fieldSelector)  # type String
    Swagger.set_param(_ctx.query, "labelSelector", labelSelector)  # type String
    Swagger.set_param(_ctx.query, "limit", limit)  # type Int32
    Swagger.set_param(_ctx.query, "resourceVersion", resourceVersion)  # type String
    Swagger.set_param(_ctx.query, "resourceVersionMatch", resourceVersionMatch)  # type String
    Swagger.set_param(_ctx.query, "timeoutSeconds", timeoutSeconds)  # type Int32
    Swagger.set_param(_ctx.query, "watch", watch)  # type Bool
    Swagger.set_header_accept(_ctx, ["application/json", "application/yaml"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", "application/yaml"] : [_mediaType])
    return _ctx
end

"""

list objects of kind Provisioner
Param: pretty::String
Param: allowWatchBookmarks::Bool
Param: __continue__::String
Param: fieldSelector::String
Param: labelSelector::String
Param: limit::Int32
Param: resourceVersion::String
Param: resourceVersionMatch::String
Param: timeoutSeconds::Int32
Param: watch::Bool
Return: ShKarpenterV1alpha5ProvisionerList
"""
function listKarpenterShV1alpha5Provisioner(_api::KarpenterShV1alpha5Api; pretty=nothing, allowWatchBookmarks=nothing, __continue__=nothing, fieldSelector=nothing, labelSelector=nothing, limit=nothing, resourceVersion=nothing, resourceVersionMatch=nothing, timeoutSeconds=nothing, watch=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_listKarpenterShV1alpha5Provisioner(_api; pretty=pretty, allowWatchBookmarks=allowWatchBookmarks, __continue__=__continue__, fieldSelector=fieldSelector, labelSelector=labelSelector, limit=limit, resourceVersion=resourceVersion, resourceVersionMatch=resourceVersionMatch, timeoutSeconds=timeoutSeconds, watch=watch, _mediaType=_mediaType)
    Swagger.exec(_ctx)
end

function listKarpenterShV1alpha5Provisioner(_api::KarpenterShV1alpha5Api, response_stream::Channel; pretty=nothing, allowWatchBookmarks=nothing, __continue__=nothing, fieldSelector=nothing, labelSelector=nothing, limit=nothing, resourceVersion=nothing, resourceVersionMatch=nothing, timeoutSeconds=nothing, watch=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_listKarpenterShV1alpha5Provisioner(_api; pretty=pretty, allowWatchBookmarks=allowWatchBookmarks, __continue__=__continue__, fieldSelector=fieldSelector, labelSelector=labelSelector, limit=limit, resourceVersion=resourceVersion, resourceVersionMatch=resourceVersionMatch, timeoutSeconds=timeoutSeconds, watch=watch, _mediaType=_mediaType)
    Swagger.exec(_ctx, response_stream)
end

function _swaggerinternal_patchKarpenterShV1alpha5Provisioner(_api::KarpenterShV1alpha5Api, name::String, body; pretty=nothing, dryRun=nothing, fieldManager=nothing, _mediaType=nothing)
    _ctx = Swagger.Ctx(_api.client, "PATCH", ShKarpenterV1alpha5Provisioner, "/apis/karpenter.sh/v1alpha5/provisioners/{name}", ["BearerToken"], body)
    Swagger.set_param(_ctx.path, "name", name)  # type String
    Swagger.set_param(_ctx.query, "pretty", pretty)  # type String
    Swagger.set_param(_ctx.query, "dryRun", dryRun)  # type String
    Swagger.set_param(_ctx.query, "fieldManager", fieldManager)  # type String
    Swagger.set_header_accept(_ctx, ["application/json", "application/yaml"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json-patch+json", "application/merge-patch+json", "application/apply-patch+yaml"] : [_mediaType])
    return _ctx
end

"""

partially update the specified Provisioner
Param: name::String (required)
Param: body::IoK8sApimachineryPkgApisMetaV1Patch (required)
Param: pretty::String
Param: dryRun::String
Param: fieldManager::String
Return: ShKarpenterV1alpha5Provisioner
"""
function patchKarpenterShV1alpha5Provisioner(_api::KarpenterShV1alpha5Api, name::String, body; pretty=nothing, dryRun=nothing, fieldManager=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_patchKarpenterShV1alpha5Provisioner(_api, name, body; pretty=pretty, dryRun=dryRun, fieldManager=fieldManager, _mediaType=_mediaType)
    Swagger.exec(_ctx)
end

function patchKarpenterShV1alpha5Provisioner(_api::KarpenterShV1alpha5Api, response_stream::Channel, name::String, body; pretty=nothing, dryRun=nothing, fieldManager=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_patchKarpenterShV1alpha5Provisioner(_api, name, body; pretty=pretty, dryRun=dryRun, fieldManager=fieldManager, _mediaType=_mediaType)
    Swagger.exec(_ctx, response_stream)
end

function _swaggerinternal_patchKarpenterShV1alpha5ProvisionerStatus(_api::KarpenterShV1alpha5Api, name::String, body; pretty=nothing, dryRun=nothing, fieldManager=nothing, _mediaType=nothing)
    _ctx = Swagger.Ctx(_api.client, "PATCH", ShKarpenterV1alpha5Provisioner, "/apis/karpenter.sh/v1alpha5/provisioners/{name}/status", ["BearerToken"], body)
    Swagger.set_param(_ctx.path, "name", name)  # type String
    Swagger.set_param(_ctx.query, "pretty", pretty)  # type String
    Swagger.set_param(_ctx.query, "dryRun", dryRun)  # type String
    Swagger.set_param(_ctx.query, "fieldManager", fieldManager)  # type String
    Swagger.set_header_accept(_ctx, ["application/json", "application/yaml"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json-patch+json", "application/merge-patch+json", "application/apply-patch+yaml"] : [_mediaType])
    return _ctx
end

"""

partially update status of the specified Provisioner
Param: name::String (required)
Param: body::IoK8sApimachineryPkgApisMetaV1Patch (required)
Param: pretty::String
Param: dryRun::String
Param: fieldManager::String
Return: ShKarpenterV1alpha5Provisioner
"""
function patchKarpenterShV1alpha5ProvisionerStatus(_api::KarpenterShV1alpha5Api, name::String, body; pretty=nothing, dryRun=nothing, fieldManager=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_patchKarpenterShV1alpha5ProvisionerStatus(_api, name, body; pretty=pretty, dryRun=dryRun, fieldManager=fieldManager, _mediaType=_mediaType)
    Swagger.exec(_ctx)
end

function patchKarpenterShV1alpha5ProvisionerStatus(_api::KarpenterShV1alpha5Api, response_stream::Channel, name::String, body; pretty=nothing, dryRun=nothing, fieldManager=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_patchKarpenterShV1alpha5ProvisionerStatus(_api, name, body; pretty=pretty, dryRun=dryRun, fieldManager=fieldManager, _mediaType=_mediaType)
    Swagger.exec(_ctx, response_stream)
end

function _swaggerinternal_readKarpenterShV1alpha5Provisioner(_api::KarpenterShV1alpha5Api, name::String; pretty=nothing, resourceVersion=nothing, _mediaType=nothing)
    _ctx = Swagger.Ctx(_api.client, "GET", ShKarpenterV1alpha5Provisioner, "/apis/karpenter.sh/v1alpha5/provisioners/{name}", ["BearerToken"])
    Swagger.set_param(_ctx.path, "name", name)  # type String
    Swagger.set_param(_ctx.query, "pretty", pretty)  # type String
    Swagger.set_param(_ctx.query, "resourceVersion", resourceVersion)  # type String
    Swagger.set_header_accept(_ctx, ["application/json", "application/yaml"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", "application/yaml"] : [_mediaType])
    return _ctx
end

"""

read the specified Provisioner
Param: name::String (required)
Param: pretty::String
Param: resourceVersion::String
Return: ShKarpenterV1alpha5Provisioner
"""
function readKarpenterShV1alpha5Provisioner(_api::KarpenterShV1alpha5Api, name::String; pretty=nothing, resourceVersion=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_readKarpenterShV1alpha5Provisioner(_api, name; pretty=pretty, resourceVersion=resourceVersion, _mediaType=_mediaType)
    Swagger.exec(_ctx)
end

function readKarpenterShV1alpha5Provisioner(_api::KarpenterShV1alpha5Api, response_stream::Channel, name::String; pretty=nothing, resourceVersion=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_readKarpenterShV1alpha5Provisioner(_api, name; pretty=pretty, resourceVersion=resourceVersion, _mediaType=_mediaType)
    Swagger.exec(_ctx, response_stream)
end

function _swaggerinternal_readKarpenterShV1alpha5ProvisionerStatus(_api::KarpenterShV1alpha5Api, name::String; pretty=nothing, resourceVersion=nothing, _mediaType=nothing)
    _ctx = Swagger.Ctx(_api.client, "GET", ShKarpenterV1alpha5Provisioner, "/apis/karpenter.sh/v1alpha5/provisioners/{name}/status", ["BearerToken"])
    Swagger.set_param(_ctx.path, "name", name)  # type String
    Swagger.set_param(_ctx.query, "pretty", pretty)  # type String
    Swagger.set_param(_ctx.query, "resourceVersion", resourceVersion)  # type String
    Swagger.set_header_accept(_ctx, ["application/json", "application/yaml"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", "application/yaml"] : [_mediaType])
    return _ctx
end

"""

read status of the specified Provisioner
Param: name::String (required)
Param: pretty::String
Param: resourceVersion::String
Return: ShKarpenterV1alpha5Provisioner
"""
function readKarpenterShV1alpha5ProvisionerStatus(_api::KarpenterShV1alpha5Api, name::String; pretty=nothing, resourceVersion=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_readKarpenterShV1alpha5ProvisionerStatus(_api, name; pretty=pretty, resourceVersion=resourceVersion, _mediaType=_mediaType)
    Swagger.exec(_ctx)
end

function readKarpenterShV1alpha5ProvisionerStatus(_api::KarpenterShV1alpha5Api, response_stream::Channel, name::String; pretty=nothing, resourceVersion=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_readKarpenterShV1alpha5ProvisionerStatus(_api, name; pretty=pretty, resourceVersion=resourceVersion, _mediaType=_mediaType)
    Swagger.exec(_ctx, response_stream)
end

function _swaggerinternal_replaceKarpenterShV1alpha5Provisioner(_api::KarpenterShV1alpha5Api, name::String, body; pretty=nothing, dryRun=nothing, fieldManager=nothing, _mediaType=nothing)
    _ctx = Swagger.Ctx(_api.client, "PUT", ShKarpenterV1alpha5Provisioner, "/apis/karpenter.sh/v1alpha5/provisioners/{name}", ["BearerToken"], body)
    Swagger.set_param(_ctx.path, "name", name)  # type String
    Swagger.set_param(_ctx.query, "pretty", pretty)  # type String
    Swagger.set_param(_ctx.query, "dryRun", dryRun)  # type String
    Swagger.set_param(_ctx.query, "fieldManager", fieldManager)  # type String
    Swagger.set_header_accept(_ctx, ["application/json", "application/yaml"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", "application/yaml"] : [_mediaType])
    return _ctx
end

"""

replace the specified Provisioner
Param: name::String (required)
Param: body::ShKarpenterV1alpha5Provisioner (required)
Param: pretty::String
Param: dryRun::String
Param: fieldManager::String
Return: ShKarpenterV1alpha5Provisioner
"""
function replaceKarpenterShV1alpha5Provisioner(_api::KarpenterShV1alpha5Api, name::String, body; pretty=nothing, dryRun=nothing, fieldManager=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_replaceKarpenterShV1alpha5Provisioner(_api, name, body; pretty=pretty, dryRun=dryRun, fieldManager=fieldManager, _mediaType=_mediaType)
    Swagger.exec(_ctx)
end

function replaceKarpenterShV1alpha5Provisioner(_api::KarpenterShV1alpha5Api, response_stream::Channel, name::String, body; pretty=nothing, dryRun=nothing, fieldManager=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_replaceKarpenterShV1alpha5Provisioner(_api, name, body; pretty=pretty, dryRun=dryRun, fieldManager=fieldManager, _mediaType=_mediaType)
    Swagger.exec(_ctx, response_stream)
end

function _swaggerinternal_replaceKarpenterShV1alpha5ProvisionerStatus(_api::KarpenterShV1alpha5Api, name::String, body; pretty=nothing, dryRun=nothing, fieldManager=nothing, _mediaType=nothing)
    _ctx = Swagger.Ctx(_api.client, "PUT", ShKarpenterV1alpha5Provisioner, "/apis/karpenter.sh/v1alpha5/provisioners/{name}/status", ["BearerToken"], body)
    Swagger.set_param(_ctx.path, "name", name)  # type String
    Swagger.set_param(_ctx.query, "pretty", pretty)  # type String
    Swagger.set_param(_ctx.query, "dryRun", dryRun)  # type String
    Swagger.set_param(_ctx.query, "fieldManager", fieldManager)  # type String
    Swagger.set_header_accept(_ctx, ["application/json", "application/yaml"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", "application/yaml"] : [_mediaType])
    return _ctx
end

"""

replace status of the specified Provisioner
Param: name::String (required)
Param: body::ShKarpenterV1alpha5Provisioner (required)
Param: pretty::String
Param: dryRun::String
Param: fieldManager::String
Return: ShKarpenterV1alpha5Provisioner
"""
function replaceKarpenterShV1alpha5ProvisionerStatus(_api::KarpenterShV1alpha5Api, name::String, body; pretty=nothing, dryRun=nothing, fieldManager=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_replaceKarpenterShV1alpha5ProvisionerStatus(_api, name, body; pretty=pretty, dryRun=dryRun, fieldManager=fieldManager, _mediaType=_mediaType)
    Swagger.exec(_ctx)
end

function replaceKarpenterShV1alpha5ProvisionerStatus(_api::KarpenterShV1alpha5Api, response_stream::Channel, name::String, body; pretty=nothing, dryRun=nothing, fieldManager=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_replaceKarpenterShV1alpha5ProvisionerStatus(_api, name, body; pretty=pretty, dryRun=dryRun, fieldManager=fieldManager, _mediaType=_mediaType)
    Swagger.exec(_ctx, response_stream)
end

export createKarpenterShV1alpha5Provisioner, deleteKarpenterShV1alpha5CollectionProvisioner, deleteKarpenterShV1alpha5Provisioner, listKarpenterShV1alpha5Provisioner, patchKarpenterShV1alpha5Provisioner, patchKarpenterShV1alpha5ProvisionerStatus, readKarpenterShV1alpha5Provisioner, readKarpenterShV1alpha5ProvisionerStatus, replaceKarpenterShV1alpha5Provisioner, replaceKarpenterShV1alpha5ProvisionerStatus
