# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

struct OpenidApi <: SwaggerApi
    client::Swagger.Client
end

function _swaggerinternal_getServiceAccountIssuerOpenIDKeyset(_api::OpenidApi; _mediaType=nothing)
    _ctx = Swagger.Ctx(_api.client, "GET", String, "/openid/v1/jwks/", ["BearerToken"])
    Swagger.set_header_accept(_ctx, ["application/jwk-set+json"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

"""

get service account issuer OpenID JSON Web Key Set (contains public token verification keys)
Return: String
"""
function getServiceAccountIssuerOpenIDKeyset(_api::OpenidApi; _mediaType=nothing)
    _ctx = _swaggerinternal_getServiceAccountIssuerOpenIDKeyset(_api; _mediaType=_mediaType)
    Swagger.exec(_ctx)
end

function getServiceAccountIssuerOpenIDKeyset(_api::OpenidApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _swaggerinternal_getServiceAccountIssuerOpenIDKeyset(_api; _mediaType=_mediaType)
    Swagger.exec(_ctx, response_stream)
end

export getServiceAccountIssuerOpenIDKeyset
