# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

struct CrdK8sAmazonawsComV1alpha1Api <: SwaggerApi
    client::Swagger.Client
end

function _swaggerinternal_createCrdK8sAmazonawsComV1alpha1ENIConfig(_api::CrdK8sAmazonawsComV1alpha1Api, body; pretty=nothing, dryRun=nothing, fieldManager=nothing, _mediaType=nothing)
    _ctx = Swagger.Ctx(_api.client, "POST", ComAmazonawsK8sCrdV1alpha1ENIConfig, "/apis/crd.k8s.amazonaws.com/v1alpha1/eniconfigs", ["BearerToken"], body)
    Swagger.set_param(_ctx.query, "pretty", pretty)  # type String
    Swagger.set_param(_ctx.query, "dryRun", dryRun)  # type String
    Swagger.set_param(_ctx.query, "fieldManager", fieldManager)  # type String
    Swagger.set_header_accept(_ctx, ["application/json", "application/yaml"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", "application/yaml"] : [_mediaType])
    return _ctx
end

"""

create an ENIConfig
Param: body::ComAmazonawsK8sCrdV1alpha1ENIConfig (required)
Param: pretty::String
Param: dryRun::String
Param: fieldManager::String
Return: ComAmazonawsK8sCrdV1alpha1ENIConfig
"""
function createCrdK8sAmazonawsComV1alpha1ENIConfig(_api::CrdK8sAmazonawsComV1alpha1Api, body; pretty=nothing, dryRun=nothing, fieldManager=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_createCrdK8sAmazonawsComV1alpha1ENIConfig(_api, body; pretty=pretty, dryRun=dryRun, fieldManager=fieldManager, _mediaType=_mediaType)
    Swagger.exec(_ctx)
end

function createCrdK8sAmazonawsComV1alpha1ENIConfig(_api::CrdK8sAmazonawsComV1alpha1Api, response_stream::Channel, body; pretty=nothing, dryRun=nothing, fieldManager=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_createCrdK8sAmazonawsComV1alpha1ENIConfig(_api, body; pretty=pretty, dryRun=dryRun, fieldManager=fieldManager, _mediaType=_mediaType)
    Swagger.exec(_ctx, response_stream)
end

function _swaggerinternal_deleteCrdK8sAmazonawsComV1alpha1CollectionENIConfig(_api::CrdK8sAmazonawsComV1alpha1Api; pretty=nothing, allowWatchBookmarks=nothing, __continue__=nothing, fieldSelector=nothing, labelSelector=nothing, limit=nothing, resourceVersion=nothing, resourceVersionMatch=nothing, timeoutSeconds=nothing, watch=nothing, _mediaType=nothing)
    _ctx = Swagger.Ctx(_api.client, "DELETE", IoK8sApimachineryPkgApisMetaV1StatusV2, "/apis/crd.k8s.amazonaws.com/v1alpha1/eniconfigs", ["BearerToken"])
    Swagger.set_param(_ctx.query, "pretty", pretty)  # type String
    Swagger.set_param(_ctx.query, "allowWatchBookmarks", allowWatchBookmarks)  # type Bool
    Swagger.set_param(_ctx.query, "continue", __continue__)  # type String
    Swagger.set_param(_ctx.query, "fieldSelector", fieldSelector)  # type String
    Swagger.set_param(_ctx.query, "labelSelector", labelSelector)  # type String
    Swagger.set_param(_ctx.query, "limit", limit)  # type Int32
    Swagger.set_param(_ctx.query, "resourceVersion", resourceVersion)  # type String
    Swagger.set_param(_ctx.query, "resourceVersionMatch", resourceVersionMatch)  # type String
    Swagger.set_param(_ctx.query, "timeoutSeconds", timeoutSeconds)  # type Int32
    Swagger.set_param(_ctx.query, "watch", watch)  # type Bool
    Swagger.set_header_accept(_ctx, ["application/json", "application/yaml"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", "application/yaml"] : [_mediaType])
    return _ctx
end

"""

delete collection of ENIConfig
Param: pretty::String
Param: allowWatchBookmarks::Bool
Param: __continue__::String
Param: fieldSelector::String
Param: labelSelector::String
Param: limit::Int32
Param: resourceVersion::String
Param: resourceVersionMatch::String
Param: timeoutSeconds::Int32
Param: watch::Bool
Return: IoK8sApimachineryPkgApisMetaV1StatusV2
"""
function deleteCrdK8sAmazonawsComV1alpha1CollectionENIConfig(_api::CrdK8sAmazonawsComV1alpha1Api; pretty=nothing, allowWatchBookmarks=nothing, __continue__=nothing, fieldSelector=nothing, labelSelector=nothing, limit=nothing, resourceVersion=nothing, resourceVersionMatch=nothing, timeoutSeconds=nothing, watch=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_deleteCrdK8sAmazonawsComV1alpha1CollectionENIConfig(_api; pretty=pretty, allowWatchBookmarks=allowWatchBookmarks, __continue__=__continue__, fieldSelector=fieldSelector, labelSelector=labelSelector, limit=limit, resourceVersion=resourceVersion, resourceVersionMatch=resourceVersionMatch, timeoutSeconds=timeoutSeconds, watch=watch, _mediaType=_mediaType)
    Swagger.exec(_ctx)
end

function deleteCrdK8sAmazonawsComV1alpha1CollectionENIConfig(_api::CrdK8sAmazonawsComV1alpha1Api, response_stream::Channel; pretty=nothing, allowWatchBookmarks=nothing, __continue__=nothing, fieldSelector=nothing, labelSelector=nothing, limit=nothing, resourceVersion=nothing, resourceVersionMatch=nothing, timeoutSeconds=nothing, watch=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_deleteCrdK8sAmazonawsComV1alpha1CollectionENIConfig(_api; pretty=pretty, allowWatchBookmarks=allowWatchBookmarks, __continue__=__continue__, fieldSelector=fieldSelector, labelSelector=labelSelector, limit=limit, resourceVersion=resourceVersion, resourceVersionMatch=resourceVersionMatch, timeoutSeconds=timeoutSeconds, watch=watch, _mediaType=_mediaType)
    Swagger.exec(_ctx, response_stream)
end

function _swaggerinternal_deleteCrdK8sAmazonawsComV1alpha1ENIConfig(_api::CrdK8sAmazonawsComV1alpha1Api, name::String; pretty=nothing, body=nothing, dryRun=nothing, gracePeriodSeconds=nothing, orphanDependents=nothing, propagationPolicy=nothing, _mediaType=nothing)
    _ctx = Swagger.Ctx(_api.client, "DELETE", IoK8sApimachineryPkgApisMetaV1StatusV2, "/apis/crd.k8s.amazonaws.com/v1alpha1/eniconfigs/{name}", ["BearerToken"], body)
    Swagger.set_param(_ctx.path, "name", name)  # type String
    Swagger.set_param(_ctx.query, "pretty", pretty)  # type String
    Swagger.set_param(_ctx.query, "dryRun", dryRun)  # type String
    Swagger.set_param(_ctx.query, "gracePeriodSeconds", gracePeriodSeconds)  # type Int32
    Swagger.set_param(_ctx.query, "orphanDependents", orphanDependents)  # type Bool
    Swagger.set_param(_ctx.query, "propagationPolicy", propagationPolicy)  # type String
    Swagger.set_header_accept(_ctx, ["application/json", "application/yaml"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", "application/yaml"] : [_mediaType])
    return _ctx
end

"""

delete an ENIConfig
Param: name::String (required)
Param: pretty::String
Param: body::IoK8sApimachineryPkgApisMetaV1DeleteOptionsV2
Param: dryRun::String
Param: gracePeriodSeconds::Int32
Param: orphanDependents::Bool
Param: propagationPolicy::String
Return: IoK8sApimachineryPkgApisMetaV1StatusV2
"""
function deleteCrdK8sAmazonawsComV1alpha1ENIConfig(_api::CrdK8sAmazonawsComV1alpha1Api, name::String; pretty=nothing, body=nothing, dryRun=nothing, gracePeriodSeconds=nothing, orphanDependents=nothing, propagationPolicy=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_deleteCrdK8sAmazonawsComV1alpha1ENIConfig(_api, name; pretty=pretty, body=body, dryRun=dryRun, gracePeriodSeconds=gracePeriodSeconds, orphanDependents=orphanDependents, propagationPolicy=propagationPolicy, _mediaType=_mediaType)
    Swagger.exec(_ctx)
end

function deleteCrdK8sAmazonawsComV1alpha1ENIConfig(_api::CrdK8sAmazonawsComV1alpha1Api, response_stream::Channel, name::String; pretty=nothing, body=nothing, dryRun=nothing, gracePeriodSeconds=nothing, orphanDependents=nothing, propagationPolicy=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_deleteCrdK8sAmazonawsComV1alpha1ENIConfig(_api, name; pretty=pretty, body=body, dryRun=dryRun, gracePeriodSeconds=gracePeriodSeconds, orphanDependents=orphanDependents, propagationPolicy=propagationPolicy, _mediaType=_mediaType)
    Swagger.exec(_ctx, response_stream)
end

function _swaggerinternal_listCrdK8sAmazonawsComV1alpha1ENIConfig(_api::CrdK8sAmazonawsComV1alpha1Api; pretty=nothing, allowWatchBookmarks=nothing, __continue__=nothing, fieldSelector=nothing, labelSelector=nothing, limit=nothing, resourceVersion=nothing, resourceVersionMatch=nothing, timeoutSeconds=nothing, watch=nothing, _mediaType=nothing)
    _ctx = Swagger.Ctx(_api.client, "GET", ComAmazonawsK8sCrdV1alpha1ENIConfigList, "/apis/crd.k8s.amazonaws.com/v1alpha1/eniconfigs", ["BearerToken"])
    Swagger.set_param(_ctx.query, "pretty", pretty)  # type String
    Swagger.set_param(_ctx.query, "allowWatchBookmarks", allowWatchBookmarks)  # type Bool
    Swagger.set_param(_ctx.query, "continue", __continue__)  # type String
    Swagger.set_param(_ctx.query, "fieldSelector", fieldSelector)  # type String
    Swagger.set_param(_ctx.query, "labelSelector", labelSelector)  # type String
    Swagger.set_param(_ctx.query, "limit", limit)  # type Int32
    Swagger.set_param(_ctx.query, "resourceVersion", resourceVersion)  # type String
    Swagger.set_param(_ctx.query, "resourceVersionMatch", resourceVersionMatch)  # type String
    Swagger.set_param(_ctx.query, "timeoutSeconds", timeoutSeconds)  # type Int32
    Swagger.set_param(_ctx.query, "watch", watch)  # type Bool
    Swagger.set_header_accept(_ctx, ["application/json", "application/yaml"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", "application/yaml"] : [_mediaType])
    return _ctx
end

"""

list objects of kind ENIConfig
Param: pretty::String
Param: allowWatchBookmarks::Bool
Param: __continue__::String
Param: fieldSelector::String
Param: labelSelector::String
Param: limit::Int32
Param: resourceVersion::String
Param: resourceVersionMatch::String
Param: timeoutSeconds::Int32
Param: watch::Bool
Return: ComAmazonawsK8sCrdV1alpha1ENIConfigList
"""
function listCrdK8sAmazonawsComV1alpha1ENIConfig(_api::CrdK8sAmazonawsComV1alpha1Api; pretty=nothing, allowWatchBookmarks=nothing, __continue__=nothing, fieldSelector=nothing, labelSelector=nothing, limit=nothing, resourceVersion=nothing, resourceVersionMatch=nothing, timeoutSeconds=nothing, watch=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_listCrdK8sAmazonawsComV1alpha1ENIConfig(_api; pretty=pretty, allowWatchBookmarks=allowWatchBookmarks, __continue__=__continue__, fieldSelector=fieldSelector, labelSelector=labelSelector, limit=limit, resourceVersion=resourceVersion, resourceVersionMatch=resourceVersionMatch, timeoutSeconds=timeoutSeconds, watch=watch, _mediaType=_mediaType)
    Swagger.exec(_ctx)
end

function listCrdK8sAmazonawsComV1alpha1ENIConfig(_api::CrdK8sAmazonawsComV1alpha1Api, response_stream::Channel; pretty=nothing, allowWatchBookmarks=nothing, __continue__=nothing, fieldSelector=nothing, labelSelector=nothing, limit=nothing, resourceVersion=nothing, resourceVersionMatch=nothing, timeoutSeconds=nothing, watch=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_listCrdK8sAmazonawsComV1alpha1ENIConfig(_api; pretty=pretty, allowWatchBookmarks=allowWatchBookmarks, __continue__=__continue__, fieldSelector=fieldSelector, labelSelector=labelSelector, limit=limit, resourceVersion=resourceVersion, resourceVersionMatch=resourceVersionMatch, timeoutSeconds=timeoutSeconds, watch=watch, _mediaType=_mediaType)
    Swagger.exec(_ctx, response_stream)
end

function _swaggerinternal_patchCrdK8sAmazonawsComV1alpha1ENIConfig(_api::CrdK8sAmazonawsComV1alpha1Api, name::String, body; pretty=nothing, dryRun=nothing, fieldManager=nothing, _mediaType=nothing)
    _ctx = Swagger.Ctx(_api.client, "PATCH", ComAmazonawsK8sCrdV1alpha1ENIConfig, "/apis/crd.k8s.amazonaws.com/v1alpha1/eniconfigs/{name}", ["BearerToken"], body)
    Swagger.set_param(_ctx.path, "name", name)  # type String
    Swagger.set_param(_ctx.query, "pretty", pretty)  # type String
    Swagger.set_param(_ctx.query, "dryRun", dryRun)  # type String
    Swagger.set_param(_ctx.query, "fieldManager", fieldManager)  # type String
    Swagger.set_header_accept(_ctx, ["application/json", "application/yaml"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json-patch+json", "application/merge-patch+json", "application/apply-patch+yaml"] : [_mediaType])
    return _ctx
end

"""

partially update the specified ENIConfig
Param: name::String (required)
Param: body::IoK8sApimachineryPkgApisMetaV1Patch (required)
Param: pretty::String
Param: dryRun::String
Param: fieldManager::String
Return: ComAmazonawsK8sCrdV1alpha1ENIConfig
"""
function patchCrdK8sAmazonawsComV1alpha1ENIConfig(_api::CrdK8sAmazonawsComV1alpha1Api, name::String, body; pretty=nothing, dryRun=nothing, fieldManager=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_patchCrdK8sAmazonawsComV1alpha1ENIConfig(_api, name, body; pretty=pretty, dryRun=dryRun, fieldManager=fieldManager, _mediaType=_mediaType)
    Swagger.exec(_ctx)
end

function patchCrdK8sAmazonawsComV1alpha1ENIConfig(_api::CrdK8sAmazonawsComV1alpha1Api, response_stream::Channel, name::String, body; pretty=nothing, dryRun=nothing, fieldManager=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_patchCrdK8sAmazonawsComV1alpha1ENIConfig(_api, name, body; pretty=pretty, dryRun=dryRun, fieldManager=fieldManager, _mediaType=_mediaType)
    Swagger.exec(_ctx, response_stream)
end

function _swaggerinternal_readCrdK8sAmazonawsComV1alpha1ENIConfig(_api::CrdK8sAmazonawsComV1alpha1Api, name::String; pretty=nothing, resourceVersion=nothing, _mediaType=nothing)
    _ctx = Swagger.Ctx(_api.client, "GET", ComAmazonawsK8sCrdV1alpha1ENIConfig, "/apis/crd.k8s.amazonaws.com/v1alpha1/eniconfigs/{name}", ["BearerToken"])
    Swagger.set_param(_ctx.path, "name", name)  # type String
    Swagger.set_param(_ctx.query, "pretty", pretty)  # type String
    Swagger.set_param(_ctx.query, "resourceVersion", resourceVersion)  # type String
    Swagger.set_header_accept(_ctx, ["application/json", "application/yaml"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", "application/yaml"] : [_mediaType])
    return _ctx
end

"""

read the specified ENIConfig
Param: name::String (required)
Param: pretty::String
Param: resourceVersion::String
Return: ComAmazonawsK8sCrdV1alpha1ENIConfig
"""
function readCrdK8sAmazonawsComV1alpha1ENIConfig(_api::CrdK8sAmazonawsComV1alpha1Api, name::String; pretty=nothing, resourceVersion=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_readCrdK8sAmazonawsComV1alpha1ENIConfig(_api, name; pretty=pretty, resourceVersion=resourceVersion, _mediaType=_mediaType)
    Swagger.exec(_ctx)
end

function readCrdK8sAmazonawsComV1alpha1ENIConfig(_api::CrdK8sAmazonawsComV1alpha1Api, response_stream::Channel, name::String; pretty=nothing, resourceVersion=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_readCrdK8sAmazonawsComV1alpha1ENIConfig(_api, name; pretty=pretty, resourceVersion=resourceVersion, _mediaType=_mediaType)
    Swagger.exec(_ctx, response_stream)
end

function _swaggerinternal_replaceCrdK8sAmazonawsComV1alpha1ENIConfig(_api::CrdK8sAmazonawsComV1alpha1Api, name::String, body; pretty=nothing, dryRun=nothing, fieldManager=nothing, _mediaType=nothing)
    _ctx = Swagger.Ctx(_api.client, "PUT", ComAmazonawsK8sCrdV1alpha1ENIConfig, "/apis/crd.k8s.amazonaws.com/v1alpha1/eniconfigs/{name}", ["BearerToken"], body)
    Swagger.set_param(_ctx.path, "name", name)  # type String
    Swagger.set_param(_ctx.query, "pretty", pretty)  # type String
    Swagger.set_param(_ctx.query, "dryRun", dryRun)  # type String
    Swagger.set_param(_ctx.query, "fieldManager", fieldManager)  # type String
    Swagger.set_header_accept(_ctx, ["application/json", "application/yaml"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", "application/yaml"] : [_mediaType])
    return _ctx
end

"""

replace the specified ENIConfig
Param: name::String (required)
Param: body::ComAmazonawsK8sCrdV1alpha1ENIConfig (required)
Param: pretty::String
Param: dryRun::String
Param: fieldManager::String
Return: ComAmazonawsK8sCrdV1alpha1ENIConfig
"""
function replaceCrdK8sAmazonawsComV1alpha1ENIConfig(_api::CrdK8sAmazonawsComV1alpha1Api, name::String, body; pretty=nothing, dryRun=nothing, fieldManager=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_replaceCrdK8sAmazonawsComV1alpha1ENIConfig(_api, name, body; pretty=pretty, dryRun=dryRun, fieldManager=fieldManager, _mediaType=_mediaType)
    Swagger.exec(_ctx)
end

function replaceCrdK8sAmazonawsComV1alpha1ENIConfig(_api::CrdK8sAmazonawsComV1alpha1Api, response_stream::Channel, name::String, body; pretty=nothing, dryRun=nothing, fieldManager=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_replaceCrdK8sAmazonawsComV1alpha1ENIConfig(_api, name, body; pretty=pretty, dryRun=dryRun, fieldManager=fieldManager, _mediaType=_mediaType)
    Swagger.exec(_ctx, response_stream)
end

export createCrdK8sAmazonawsComV1alpha1ENIConfig, deleteCrdK8sAmazonawsComV1alpha1CollectionENIConfig, deleteCrdK8sAmazonawsComV1alpha1ENIConfig, listCrdK8sAmazonawsComV1alpha1ENIConfig, patchCrdK8sAmazonawsComV1alpha1ENIConfig, readCrdK8sAmazonawsComV1alpha1ENIConfig, replaceCrdK8sAmazonawsComV1alpha1ENIConfig
