# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


@doc raw"""CSIDriverSpec is the specification of a CSIDriver.

    IoK8sApiStorageV1CSIDriverSpec(;
        attachRequired=nothing,
        fsGroupPolicy=nothing,
        podInfoOnMount=nothing,
        requiresRepublish=nothing,
        storageCapacity=nothing,
        tokenRequests=nothing,
        volumeLifecycleModes=nothing,
    )

    - attachRequired::Bool : attachRequired indicates this CSI volume driver requires an attach operation (because it implements the CSI ControllerPublishVolume() method), and that the Kubernetes attach detach controller should call the attach volume interface which checks the volumeattachment status and waits until the volume is attached before proceeding to mounting. The CSI external-attacher coordinates with CSI volume driver and updates the volumeattachment status when the attach operation is complete. If the CSIDriverRegistry feature gate is enabled and the value is specified to false, the attach operation will be skipped. Otherwise the attach operation will be called.
    - fsGroupPolicy::String : Defines if the underlying volume supports changing ownership and permission of the volume before being mounted. Refer to the specific FSGroupPolicy values for additional details. This field is alpha-level, and is only honored by servers that enable the CSIVolumeFSGroupPolicy feature gate.
    - podInfoOnMount::Bool : If set to true, podInfoOnMount indicates this CSI volume driver requires additional pod information (like podName, podUID, etc.) during mount operations. If set to false, pod information will not be passed on mount. Default is false. The CSI driver specifies podInfoOnMount as part of driver deployment. If true, Kubelet will pass pod information as VolumeContext in the CSI NodePublishVolume() calls. The CSI driver is responsible for parsing and validating the information passed in as VolumeContext. The following VolumeConext will be passed if podInfoOnMount is set to true. This list might grow, but the prefix will be used. \&quot;csi.storage.k8s.io/pod.name\&quot;: pod.Name \&quot;csi.storage.k8s.io/pod.namespace\&quot;: pod.Namespace \&quot;csi.storage.k8s.io/pod.uid\&quot;: string(pod.UID) \&quot;csi.storage.k8s.io/ephemeral\&quot;: \&quot;true\&quot; iff the volume is an ephemeral inline volume                                 defined by a CSIVolumeSource, otherwise \&quot;false\&quot;  \&quot;csi.storage.k8s.io/ephemeral\&quot; is a new feature in Kubernetes 1.16. It is only required for drivers which support both the \&quot;Persistent\&quot; and \&quot;Ephemeral\&quot; VolumeLifecycleMode. Other drivers can leave pod info disabled and/or ignore this field. As Kubernetes 1.15 doesn&#39;t support this field, drivers can only support one mode when deployed on such a cluster and the deployment determines which mode that is, for example via a command line parameter of the driver.
    - requiresRepublish::Bool : RequiresRepublish indicates the CSI driver wants &#x60;NodePublishVolume&#x60; being periodically called to reflect any possible change in the mounted volume. This field defaults to false.  Note: After a successful initial NodePublishVolume call, subsequent calls to NodePublishVolume should only update the contents of the volume. New mount points will not be seen by a running container.  This is an alpha feature and only available when the CSIServiceAccountToken feature is enabled.
    - storageCapacity::Bool : If set to true, storageCapacity indicates that the CSI volume driver wants pod scheduling to consider the storage capacity that the driver deployment will report by creating CSIStorageCapacity objects with capacity information.  The check can be enabled immediately when deploying a driver. In that case, provisioning new volumes with late binding will pause until the driver deployment has published some suitable CSIStorageCapacity object.  Alternatively, the driver can be deployed with the field unset or false and it can be flipped later when storage capacity information has been published.  This is an alpha field and only available when the CSIStorageCapacity feature is enabled. The default is false.
    - tokenRequests::Vector{IoK8sApiStorageV1TokenRequest} : TokenRequests indicates the CSI driver needs pods&#39; service account tokens it is mounting volume for to do necessary authentication. Kubelet will pass the tokens in VolumeContext in the CSI NodePublishVolume calls. The CSI driver should parse and validate the following VolumeContext: \&quot;csi.storage.k8s.io/serviceAccount.tokens\&quot;: {   \&quot;&lt;audience&gt;\&quot;: {     \&quot;token\&quot;: &lt;token&gt;,     \&quot;expirationTimestamp\&quot;: &lt;expiration timestamp in RFC3339&gt;,   },   ... }  Note: Audience in each TokenRequest should be different and at most one token is empty string. To receive a new token after expiry, RequiresRepublish can be used to trigger NodePublishVolume periodically.  This is an alpha feature and only available when the CSIServiceAccountToken feature is enabled.
    - volumeLifecycleModes::Vector{String} : volumeLifecycleModes defines what kind of volumes this CSI volume driver supports. The default if the list is empty is \&quot;Persistent\&quot;, which is the usage defined by the CSI specification and implemented in Kubernetes via the usual PV/PVC mechanism. The other mode is \&quot;Ephemeral\&quot;. In this mode, volumes are defined inline inside the pod spec with CSIVolumeSource and their lifecycle is tied to the lifecycle of that pod. A driver has to be aware of this because it is only going to get a NodePublishVolume call for such a volume. For more information about implementing this mode, see https://kubernetes-csi.github.io/docs/ephemeral-local-volumes.html A driver can support one or more of these modes and more modes may be added in the future. This field is beta.
"""
mutable struct IoK8sApiStorageV1CSIDriverSpec <: SwaggerModel
    attachRequired::Any # spec type: Union{ Nothing, Bool } # spec name: attachRequired
    fsGroupPolicy::Any # spec type: Union{ Nothing, String } # spec name: fsGroupPolicy
    podInfoOnMount::Any # spec type: Union{ Nothing, Bool } # spec name: podInfoOnMount
    requiresRepublish::Any # spec type: Union{ Nothing, Bool } # spec name: requiresRepublish
    storageCapacity::Any # spec type: Union{ Nothing, Bool } # spec name: storageCapacity
    tokenRequests::Any # spec type: Union{ Nothing, Vector{IoK8sApiStorageV1TokenRequest} } # spec name: tokenRequests
    volumeLifecycleModes::Any # spec type: Union{ Nothing, Vector{String} } # spec name: volumeLifecycleModes

    function IoK8sApiStorageV1CSIDriverSpec(;attachRequired=nothing, fsGroupPolicy=nothing, podInfoOnMount=nothing, requiresRepublish=nothing, storageCapacity=nothing, tokenRequests=nothing, volumeLifecycleModes=nothing)
        o = new()
        validate_property(IoK8sApiStorageV1CSIDriverSpec, Symbol("attachRequired"), attachRequired)
        setfield!(o, Symbol("attachRequired"), attachRequired)
        validate_property(IoK8sApiStorageV1CSIDriverSpec, Symbol("fsGroupPolicy"), fsGroupPolicy)
        setfield!(o, Symbol("fsGroupPolicy"), fsGroupPolicy)
        validate_property(IoK8sApiStorageV1CSIDriverSpec, Symbol("podInfoOnMount"), podInfoOnMount)
        setfield!(o, Symbol("podInfoOnMount"), podInfoOnMount)
        validate_property(IoK8sApiStorageV1CSIDriverSpec, Symbol("requiresRepublish"), requiresRepublish)
        setfield!(o, Symbol("requiresRepublish"), requiresRepublish)
        validate_property(IoK8sApiStorageV1CSIDriverSpec, Symbol("storageCapacity"), storageCapacity)
        setfield!(o, Symbol("storageCapacity"), storageCapacity)
        validate_property(IoK8sApiStorageV1CSIDriverSpec, Symbol("tokenRequests"), tokenRequests)
        setfield!(o, Symbol("tokenRequests"), tokenRequests)
        validate_property(IoK8sApiStorageV1CSIDriverSpec, Symbol("volumeLifecycleModes"), volumeLifecycleModes)
        setfield!(o, Symbol("volumeLifecycleModes"), volumeLifecycleModes)
        o
    end
end # type IoK8sApiStorageV1CSIDriverSpec

const _property_map_IoK8sApiStorageV1CSIDriverSpec = Dict{Symbol,Symbol}(Symbol("attachRequired")=>Symbol("attachRequired"), Symbol("fsGroupPolicy")=>Symbol("fsGroupPolicy"), Symbol("podInfoOnMount")=>Symbol("podInfoOnMount"), Symbol("requiresRepublish")=>Symbol("requiresRepublish"), Symbol("storageCapacity")=>Symbol("storageCapacity"), Symbol("tokenRequests")=>Symbol("tokenRequests"), Symbol("volumeLifecycleModes")=>Symbol("volumeLifecycleModes"))
const _property_types_IoK8sApiStorageV1CSIDriverSpec = Dict{Symbol,String}(Symbol("attachRequired")=>"Bool", Symbol("fsGroupPolicy")=>"String", Symbol("podInfoOnMount")=>"Bool", Symbol("requiresRepublish")=>"Bool", Symbol("storageCapacity")=>"Bool", Symbol("tokenRequests")=>"Vector{IoK8sApiStorageV1TokenRequest}", Symbol("volumeLifecycleModes")=>"Vector{String}")
Base.propertynames(::Type{ IoK8sApiStorageV1CSIDriverSpec }) = collect(keys(_property_map_IoK8sApiStorageV1CSIDriverSpec))
Swagger.property_type(::Type{ IoK8sApiStorageV1CSIDriverSpec }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoK8sApiStorageV1CSIDriverSpec[name]))}
Swagger.field_name(::Type{ IoK8sApiStorageV1CSIDriverSpec }, property_name::Symbol) =  _property_map_IoK8sApiStorageV1CSIDriverSpec[property_name]

function check_required(o::IoK8sApiStorageV1CSIDriverSpec)
    true
end

function validate_property(::Type{ IoK8sApiStorageV1CSIDriverSpec }, name::Symbol, val)
end
