# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


@doc raw"""
    OrgProjectcalicoCrdV1NetworkPolicy(;
    )

"""
mutable struct OrgProjectcalicoCrdV1NetworkPolicy <: SwaggerModel

    function OrgProjectcalicoCrdV1NetworkPolicy(;)
        o = new()
        o
    end
end # type OrgProjectcalicoCrdV1NetworkPolicy

const _property_map_OrgProjectcalicoCrdV1NetworkPolicy = Dict{Symbol,Symbol}()
const _property_types_OrgProjectcalicoCrdV1NetworkPolicy = Dict{Symbol,String}()
Base.propertynames(::Type{ OrgProjectcalicoCrdV1NetworkPolicy }) = collect(keys(_property_map_OrgProjectcalicoCrdV1NetworkPolicy))
Swagger.property_type(::Type{ OrgProjectcalicoCrdV1NetworkPolicy }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_OrgProjectcalicoCrdV1NetworkPolicy[name]))}
Swagger.field_name(::Type{ OrgProjectcalicoCrdV1NetworkPolicy }, property_name::Symbol) =  _property_map_OrgProjectcalicoCrdV1NetworkPolicy[property_name]

function check_required(o::OrgProjectcalicoCrdV1NetworkPolicy)
    true
end

function validate_property(::Type{ OrgProjectcalicoCrdV1NetworkPolicy }, name::Symbol, val)
end
