# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


@doc raw"""ServiceSpec describes the attributes that a user creates on a service.

    IoK8sApiCoreV1ServiceSpec(;
        allocateLoadBalancerNodePorts=nothing,
        clusterIP=nothing,
        clusterIPs=nothing,
        externalIPs=nothing,
        externalName=nothing,
        externalTrafficPolicy=nothing,
        healthCheckNodePort=nothing,
        ipFamilies=nothing,
        ipFamilyPolicy=nothing,
        loadBalancerIP=nothing,
        loadBalancerSourceRanges=nothing,
        ports=nothing,
        publishNotReadyAddresses=nothing,
        selector=nothing,
        sessionAffinity=nothing,
        sessionAffinityConfig=nothing,
        topologyKeys=nothing,
        type=nothing,
    )

    - allocateLoadBalancerNodePorts::Bool : allocateLoadBalancerNodePorts defines if NodePorts will be automatically allocated for services with type LoadBalancer.  Default is \&quot;true\&quot;. It may be set to \&quot;false\&quot; if the cluster load-balancer does not rely on NodePorts. allocateLoadBalancerNodePorts may only be set for services with type LoadBalancer and will be cleared if the type is changed to any other type. This field is alpha-level and is only honored by servers that enable the ServiceLBNodePortControl feature.
    - clusterIP::String : clusterIP is the IP address of the service and is usually assigned randomly. If an address is specified manually, is in-range (as per system configuration), and is not in use, it will be allocated to the service; otherwise creation of the service will fail. This field may not be changed through updates unless the type field is also being changed to ExternalName (which requires this field to be blank) or the type field is being changed from ExternalName (in which case this field may optionally be specified, as describe above).  Valid values are \&quot;None\&quot;, empty string (\&quot;\&quot;), or a valid IP address. Setting this to \&quot;None\&quot; makes a \&quot;headless service\&quot; (no virtual IP), which is useful when direct endpoint connections are preferred and proxying is not required.  Only applies to types ClusterIP, NodePort, and LoadBalancer. If this field is specified when creating a Service of type ExternalName, creation will fail. This field will be wiped when updating a Service to type ExternalName. More info: https://kubernetes.io/docs/concepts/services-networking/service/#virtual-ips-and-service-proxies
    - clusterIPs::Vector{String} : ClusterIPs is a list of IP addresses assigned to this service, and are usually assigned randomly.  If an address is specified manually, is in-range (as per system configuration), and is not in use, it will be allocated to the service; otherwise creation of the service will fail. This field may not be changed through updates unless the type field is also being changed to ExternalName (which requires this field to be empty) or the type field is being changed from ExternalName (in which case this field may optionally be specified, as describe above).  Valid values are \&quot;None\&quot;, empty string (\&quot;\&quot;), or a valid IP address.  Setting this to \&quot;None\&quot; makes a \&quot;headless service\&quot; (no virtual IP), which is useful when direct endpoint connections are preferred and proxying is not required.  Only applies to types ClusterIP, NodePort, and LoadBalancer. If this field is specified when creating a Service of type ExternalName, creation will fail. This field will be wiped when updating a Service to type ExternalName.  If this field is not specified, it will be initialized from the clusterIP field.  If this field is specified, clients must ensure that clusterIPs[0] and clusterIP have the same value.  Unless the \&quot;IPv6DualStack\&quot; feature gate is enabled, this field is limited to one value, which must be the same as the clusterIP field.  If the feature gate is enabled, this field may hold a maximum of two entries (dual-stack IPs, in either order).  These IPs must correspond to the values of the ipFamilies field. Both clusterIPs and ipFamilies are governed by the ipFamilyPolicy field. More info: https://kubernetes.io/docs/concepts/services-networking/service/#virtual-ips-and-service-proxies
    - externalIPs::Vector{String} : externalIPs is a list of IP addresses for which nodes in the cluster will also accept traffic for this service.  These IPs are not managed by Kubernetes.  The user is responsible for ensuring that traffic arrives at a node with this IP.  A common example is external load-balancers that are not part of the Kubernetes system.
    - externalName::String : externalName is the external reference that discovery mechanisms will return as an alias for this service (e.g. a DNS CNAME record). No proxying will be involved.  Must be a lowercase RFC-1123 hostname (https://tools.ietf.org/html/rfc1123) and requires Type to be
    - externalTrafficPolicy::String : externalTrafficPolicy denotes if this Service desires to route external traffic to node-local or cluster-wide endpoints. \&quot;Local\&quot; preserves the client source IP and avoids a second hop for LoadBalancer and Nodeport type services, but risks potentially imbalanced traffic spreading. \&quot;Cluster\&quot; obscures the client source IP and may cause a second hop to another node, but should have good overall load-spreading.
    - healthCheckNodePort::Int32 : healthCheckNodePort specifies the healthcheck nodePort for the service. This only applies when type is set to LoadBalancer and externalTrafficPolicy is set to Local. If a value is specified, is in-range, and is not in use, it will be used.  If not specified, a value will be automatically allocated.  External systems (e.g. load-balancers) can use this port to determine if a given node holds endpoints for this service or not.  If this field is specified when creating a Service which does not need it, creation will fail. This field will be wiped when updating a Service to no longer need it (e.g. changing type).
    - ipFamilies::Vector{String} : IPFamilies is a list of IP families (e.g. IPv4, IPv6) assigned to this service, and is gated by the \&quot;IPv6DualStack\&quot; feature gate.  This field is usually assigned automatically based on cluster configuration and the ipFamilyPolicy field. If this field is specified manually, the requested family is available in the cluster, and ipFamilyPolicy allows it, it will be used; otherwise creation of the service will fail.  This field is conditionally mutable: it allows for adding or removing a secondary IP family, but it does not allow changing the primary IP family of the Service.  Valid values are \&quot;IPv4\&quot; and \&quot;IPv6\&quot;.  This field only applies to Services of types ClusterIP, NodePort, and LoadBalancer, and does apply to \&quot;headless\&quot; services.  This field will be wiped when updating a Service to type ExternalName.  This field may hold a maximum of two entries (dual-stack families, in either order).  These families must correspond to the values of the clusterIPs field, if specified. Both clusterIPs and ipFamilies are governed by the ipFamilyPolicy field.
    - ipFamilyPolicy::String : IPFamilyPolicy represents the dual-stack-ness requested or required by this Service, and is gated by the \&quot;IPv6DualStack\&quot; feature gate.  If there is no value provided, then this field will be set to SingleStack. Services can be \&quot;SingleStack\&quot; (a single IP family), \&quot;PreferDualStack\&quot; (two IP families on dual-stack configured clusters or a single IP family on single-stack clusters), or \&quot;RequireDualStack\&quot; (two IP families on dual-stack configured clusters, otherwise fail). The ipFamilies and clusterIPs fields depend on the value of this field.  This field will be wiped when updating a service to type ExternalName.
    - loadBalancerIP::String : Only applies to Service Type: LoadBalancer LoadBalancer will get created with the IP specified in this field. This feature depends on whether the underlying cloud-provider supports specifying the loadBalancerIP when a load balancer is created. This field will be ignored if the cloud-provider does not support the feature.
    - loadBalancerSourceRanges::Vector{String} : If specified and supported by the platform, this will restrict traffic through the cloud-provider load-balancer will be restricted to the specified client IPs. This field will be ignored if the cloud-provider does not support the feature.\&quot; More info: https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/
    - ports::Vector{IoK8sApiCoreV1ServicePort} : The list of ports that are exposed by this service. More info: https://kubernetes.io/docs/concepts/services-networking/service/#virtual-ips-and-service-proxies
    - publishNotReadyAddresses::Bool : publishNotReadyAddresses indicates that any agent which deals with endpoints for this Service should disregard any indications of ready/not-ready. The primary use case for setting this field is for a StatefulSet&#39;s Headless Service to propagate SRV DNS records for its Pods for the purpose of peer discovery. The Kubernetes controllers that generate Endpoints and EndpointSlice resources for Services interpret this to mean that all endpoints are considered \&quot;ready\&quot; even if the Pods themselves are not. Agents which consume only Kubernetes generated endpoints through the Endpoints or EndpointSlice resources can safely assume this behavior.
    - selector::Dict{String, String} : Route service traffic to pods with label keys and values matching this selector. If empty or not present, the service is assumed to have an external process managing its endpoints, which Kubernetes will not modify. Only applies to types ClusterIP, NodePort, and LoadBalancer. Ignored if type is ExternalName. More info: https://kubernetes.io/docs/concepts/services-networking/service/
    - sessionAffinity::String : Supports \&quot;ClientIP\&quot; and \&quot;None\&quot;. Used to maintain session affinity. Enable client IP based session affinity. Must be ClientIP or None. Defaults to None. More info: https://kubernetes.io/docs/concepts/services-networking/service/#virtual-ips-and-service-proxies
    - sessionAffinityConfig::IoK8sApiCoreV1SessionAffinityConfig : sessionAffinityConfig contains the configurations of session affinity.
    - topologyKeys::Vector{String} : topologyKeys is a preference-order list of topology keys which implementations of services should use to preferentially sort endpoints when accessing this Service, it can not be used at the same time as externalTrafficPolicy&#x3D;Local. Topology keys must be valid label keys and at most 16 keys may be specified. Endpoints are chosen based on the first topology key with available backends. If this field is specified and all entries have no backends that match the topology of the client, the service has no backends for that client and connections should fail. The special value \&quot;*\&quot; may be used to mean \&quot;any topology\&quot;. This catch-all value, if used, only makes sense as the last value in the list. If this is not specified or empty, no topology constraints will be applied. This field is alpha-level and is only honored by servers that enable the ServiceTopology feature.
    - type::String : type determines how the Service is exposed. Defaults to ClusterIP. Valid options are ExternalName, ClusterIP, NodePort, and LoadBalancer. \&quot;ClusterIP\&quot; allocates a cluster-internal IP address for load-balancing to endpoints. Endpoints are determined by the selector or if that is not specified, by manual construction of an Endpoints object or EndpointSlice objects. If clusterIP is \&quot;None\&quot;, no virtual IP is allocated and the endpoints are published as a set of endpoints rather than a virtual IP. \&quot;NodePort\&quot; builds on ClusterIP and allocates a port on every node which routes to the same endpoints as the clusterIP. \&quot;LoadBalancer\&quot; builds on NodePort and creates an external load-balancer (if supported in the current cloud) which routes to the same endpoints as the clusterIP. \&quot;ExternalName\&quot; aliases this service to the specified externalName. Several other fields do not apply to ExternalName services. More info: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
"""
mutable struct IoK8sApiCoreV1ServiceSpec <: SwaggerModel
    allocateLoadBalancerNodePorts::Any # spec type: Union{ Nothing, Bool } # spec name: allocateLoadBalancerNodePorts
    clusterIP::Any # spec type: Union{ Nothing, String } # spec name: clusterIP
    clusterIPs::Any # spec type: Union{ Nothing, Vector{String} } # spec name: clusterIPs
    externalIPs::Any # spec type: Union{ Nothing, Vector{String} } # spec name: externalIPs
    externalName::Any # spec type: Union{ Nothing, String } # spec name: externalName
    externalTrafficPolicy::Any # spec type: Union{ Nothing, String } # spec name: externalTrafficPolicy
    healthCheckNodePort::Any # spec type: Union{ Nothing, Int32 } # spec name: healthCheckNodePort
    ipFamilies::Any # spec type: Union{ Nothing, Vector{String} } # spec name: ipFamilies
    ipFamilyPolicy::Any # spec type: Union{ Nothing, String } # spec name: ipFamilyPolicy
    loadBalancerIP::Any # spec type: Union{ Nothing, String } # spec name: loadBalancerIP
    loadBalancerSourceRanges::Any # spec type: Union{ Nothing, Vector{String} } # spec name: loadBalancerSourceRanges
    ports::Any # spec type: Union{ Nothing, Vector{IoK8sApiCoreV1ServicePort} } # spec name: ports
    publishNotReadyAddresses::Any # spec type: Union{ Nothing, Bool } # spec name: publishNotReadyAddresses
    selector::Any # spec type: Union{ Nothing, Dict{String, String} } # spec name: selector
    sessionAffinity::Any # spec type: Union{ Nothing, String } # spec name: sessionAffinity
    sessionAffinityConfig::Any # spec type: Union{ Nothing, IoK8sApiCoreV1SessionAffinityConfig } # spec name: sessionAffinityConfig
    topologyKeys::Any # spec type: Union{ Nothing, Vector{String} } # spec name: topologyKeys
    type::Any # spec type: Union{ Nothing, String } # spec name: type

    function IoK8sApiCoreV1ServiceSpec(;allocateLoadBalancerNodePorts=nothing, clusterIP=nothing, clusterIPs=nothing, externalIPs=nothing, externalName=nothing, externalTrafficPolicy=nothing, healthCheckNodePort=nothing, ipFamilies=nothing, ipFamilyPolicy=nothing, loadBalancerIP=nothing, loadBalancerSourceRanges=nothing, ports=nothing, publishNotReadyAddresses=nothing, selector=nothing, sessionAffinity=nothing, sessionAffinityConfig=nothing, topologyKeys=nothing, type=nothing)
        o = new()
        validate_property(IoK8sApiCoreV1ServiceSpec, Symbol("allocateLoadBalancerNodePorts"), allocateLoadBalancerNodePorts)
        setfield!(o, Symbol("allocateLoadBalancerNodePorts"), allocateLoadBalancerNodePorts)
        validate_property(IoK8sApiCoreV1ServiceSpec, Symbol("clusterIP"), clusterIP)
        setfield!(o, Symbol("clusterIP"), clusterIP)
        validate_property(IoK8sApiCoreV1ServiceSpec, Symbol("clusterIPs"), clusterIPs)
        setfield!(o, Symbol("clusterIPs"), clusterIPs)
        validate_property(IoK8sApiCoreV1ServiceSpec, Symbol("externalIPs"), externalIPs)
        setfield!(o, Symbol("externalIPs"), externalIPs)
        validate_property(IoK8sApiCoreV1ServiceSpec, Symbol("externalName"), externalName)
        setfield!(o, Symbol("externalName"), externalName)
        validate_property(IoK8sApiCoreV1ServiceSpec, Symbol("externalTrafficPolicy"), externalTrafficPolicy)
        setfield!(o, Symbol("externalTrafficPolicy"), externalTrafficPolicy)
        validate_property(IoK8sApiCoreV1ServiceSpec, Symbol("healthCheckNodePort"), healthCheckNodePort)
        setfield!(o, Symbol("healthCheckNodePort"), healthCheckNodePort)
        validate_property(IoK8sApiCoreV1ServiceSpec, Symbol("ipFamilies"), ipFamilies)
        setfield!(o, Symbol("ipFamilies"), ipFamilies)
        validate_property(IoK8sApiCoreV1ServiceSpec, Symbol("ipFamilyPolicy"), ipFamilyPolicy)
        setfield!(o, Symbol("ipFamilyPolicy"), ipFamilyPolicy)
        validate_property(IoK8sApiCoreV1ServiceSpec, Symbol("loadBalancerIP"), loadBalancerIP)
        setfield!(o, Symbol("loadBalancerIP"), loadBalancerIP)
        validate_property(IoK8sApiCoreV1ServiceSpec, Symbol("loadBalancerSourceRanges"), loadBalancerSourceRanges)
        setfield!(o, Symbol("loadBalancerSourceRanges"), loadBalancerSourceRanges)
        validate_property(IoK8sApiCoreV1ServiceSpec, Symbol("ports"), ports)
        setfield!(o, Symbol("ports"), ports)
        validate_property(IoK8sApiCoreV1ServiceSpec, Symbol("publishNotReadyAddresses"), publishNotReadyAddresses)
        setfield!(o, Symbol("publishNotReadyAddresses"), publishNotReadyAddresses)
        validate_property(IoK8sApiCoreV1ServiceSpec, Symbol("selector"), selector)
        setfield!(o, Symbol("selector"), selector)
        validate_property(IoK8sApiCoreV1ServiceSpec, Symbol("sessionAffinity"), sessionAffinity)
        setfield!(o, Symbol("sessionAffinity"), sessionAffinity)
        validate_property(IoK8sApiCoreV1ServiceSpec, Symbol("sessionAffinityConfig"), sessionAffinityConfig)
        setfield!(o, Symbol("sessionAffinityConfig"), sessionAffinityConfig)
        validate_property(IoK8sApiCoreV1ServiceSpec, Symbol("topologyKeys"), topologyKeys)
        setfield!(o, Symbol("topologyKeys"), topologyKeys)
        validate_property(IoK8sApiCoreV1ServiceSpec, Symbol("type"), type)
        setfield!(o, Symbol("type"), type)
        o
    end
end # type IoK8sApiCoreV1ServiceSpec

const _property_map_IoK8sApiCoreV1ServiceSpec = Dict{Symbol,Symbol}(Symbol("allocateLoadBalancerNodePorts")=>Symbol("allocateLoadBalancerNodePorts"), Symbol("clusterIP")=>Symbol("clusterIP"), Symbol("clusterIPs")=>Symbol("clusterIPs"), Symbol("externalIPs")=>Symbol("externalIPs"), Symbol("externalName")=>Symbol("externalName"), Symbol("externalTrafficPolicy")=>Symbol("externalTrafficPolicy"), Symbol("healthCheckNodePort")=>Symbol("healthCheckNodePort"), Symbol("ipFamilies")=>Symbol("ipFamilies"), Symbol("ipFamilyPolicy")=>Symbol("ipFamilyPolicy"), Symbol("loadBalancerIP")=>Symbol("loadBalancerIP"), Symbol("loadBalancerSourceRanges")=>Symbol("loadBalancerSourceRanges"), Symbol("ports")=>Symbol("ports"), Symbol("publishNotReadyAddresses")=>Symbol("publishNotReadyAddresses"), Symbol("selector")=>Symbol("selector"), Symbol("sessionAffinity")=>Symbol("sessionAffinity"), Symbol("sessionAffinityConfig")=>Symbol("sessionAffinityConfig"), Symbol("topologyKeys")=>Symbol("topologyKeys"), Symbol("type")=>Symbol("type"))
const _property_types_IoK8sApiCoreV1ServiceSpec = Dict{Symbol,String}(Symbol("allocateLoadBalancerNodePorts")=>"Bool", Symbol("clusterIP")=>"String", Symbol("clusterIPs")=>"Vector{String}", Symbol("externalIPs")=>"Vector{String}", Symbol("externalName")=>"String", Symbol("externalTrafficPolicy")=>"String", Symbol("healthCheckNodePort")=>"Int32", Symbol("ipFamilies")=>"Vector{String}", Symbol("ipFamilyPolicy")=>"String", Symbol("loadBalancerIP")=>"String", Symbol("loadBalancerSourceRanges")=>"Vector{String}", Symbol("ports")=>"Vector{IoK8sApiCoreV1ServicePort}", Symbol("publishNotReadyAddresses")=>"Bool", Symbol("selector")=>"Dict{String, String}", Symbol("sessionAffinity")=>"String", Symbol("sessionAffinityConfig")=>"IoK8sApiCoreV1SessionAffinityConfig", Symbol("topologyKeys")=>"Vector{String}", Symbol("type")=>"String")
Base.propertynames(::Type{ IoK8sApiCoreV1ServiceSpec }) = collect(keys(_property_map_IoK8sApiCoreV1ServiceSpec))
Swagger.property_type(::Type{ IoK8sApiCoreV1ServiceSpec }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoK8sApiCoreV1ServiceSpec[name]))}
Swagger.field_name(::Type{ IoK8sApiCoreV1ServiceSpec }, property_name::Symbol) =  _property_map_IoK8sApiCoreV1ServiceSpec[property_name]

function check_required(o::IoK8sApiCoreV1ServiceSpec)
    true
end

function validate_property(::Type{ IoK8sApiCoreV1ServiceSpec }, name::Symbol, val)
end
