# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


@doc raw"""HorizontalPodAutoscalerBehavior configures the scaling behavior of the target in both Up and Down directions (scaleUp and scaleDown fields respectively).

    IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerBehavior(;
        scaleDown=nothing,
        scaleUp=nothing,
    )

    - scaleDown::IoK8sApiAutoscalingV2beta2HPAScalingRules : scaleDown is scaling policy for scaling Down. If not set, the default value is to allow to scale down to minReplicas pods, with a 300 second stabilization window (i.e., the highest recommendation for the last 300sec is used).
    - scaleUp::IoK8sApiAutoscalingV2beta2HPAScalingRules : scaleUp is scaling policy for scaling Up. If not set, the default value is the higher of:   * increase no more than 4 pods per 60 seconds   * double the number of pods per 60 seconds No stabilization is used.
"""
mutable struct IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerBehavior <: SwaggerModel
    scaleDown::Any # spec type: Union{ Nothing, IoK8sApiAutoscalingV2beta2HPAScalingRules } # spec name: scaleDown
    scaleUp::Any # spec type: Union{ Nothing, IoK8sApiAutoscalingV2beta2HPAScalingRules } # spec name: scaleUp

    function IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerBehavior(;scaleDown=nothing, scaleUp=nothing)
        o = new()
        validate_property(IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerBehavior, Symbol("scaleDown"), scaleDown)
        setfield!(o, Symbol("scaleDown"), scaleDown)
        validate_property(IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerBehavior, Symbol("scaleUp"), scaleUp)
        setfield!(o, Symbol("scaleUp"), scaleUp)
        o
    end
end # type IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerBehavior

const _property_map_IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerBehavior = Dict{Symbol,Symbol}(Symbol("scaleDown")=>Symbol("scaleDown"), Symbol("scaleUp")=>Symbol("scaleUp"))
const _property_types_IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerBehavior = Dict{Symbol,String}(Symbol("scaleDown")=>"IoK8sApiAutoscalingV2beta2HPAScalingRules", Symbol("scaleUp")=>"IoK8sApiAutoscalingV2beta2HPAScalingRules")
Base.propertynames(::Type{ IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerBehavior }) = collect(keys(_property_map_IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerBehavior))
Swagger.property_type(::Type{ IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerBehavior }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerBehavior[name]))}
Swagger.field_name(::Type{ IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerBehavior }, property_name::Symbol) =  _property_map_IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerBehavior[property_name]

function check_required(o::IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerBehavior)
    true
end

function validate_property(::Type{ IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerBehavior }, name::Symbol, val)
end
