# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


@doc raw"""Represents an ephemeral volume that is handled by a normal storage driver.

    IoK8sApiCoreV1EphemeralVolumeSource(;
        readOnly=nothing,
        volumeClaimTemplate=nothing,
    )

    - readOnly::Bool : Specifies a read-only configuration for the volume. Defaults to false (read/write).
    - volumeClaimTemplate::IoK8sApiCoreV1PersistentVolumeClaimTemplate : Will be used to create a stand-alone PVC to provision the volume. The pod in which this EphemeralVolumeSource is embedded will be the owner of the PVC, i.e. the PVC will be deleted together with the pod.  The name of the PVC will be &#x60;&lt;pod name&gt;-&lt;volume name&gt;&#x60; where &#x60;&lt;volume name&gt;&#x60; is the name from the &#x60;PodSpec.Volumes&#x60; array entry. Pod validation will reject the pod if the concatenated name is not valid for a PVC (for example, too long).  An existing PVC with that name that is not owned by the pod will *not* be used for the pod to avoid using an unrelated volume by mistake. Starting the pod is then blocked until the unrelated PVC is removed. If such a pre-created PVC is meant to be used by the pod, the PVC has to updated with an owner reference to the pod once the pod exists. Normally this should not be necessary, but it may be useful when manually reconstructing a broken cluster.  This field is read-only and no changes will be made by Kubernetes to the PVC after it has been created.  Required, must not be nil.
"""
mutable struct IoK8sApiCoreV1EphemeralVolumeSource <: SwaggerModel
    readOnly::Any # spec type: Union{ Nothing, Bool } # spec name: readOnly
    volumeClaimTemplate::Any # spec type: Union{ Nothing, IoK8sApiCoreV1PersistentVolumeClaimTemplate } # spec name: volumeClaimTemplate

    function IoK8sApiCoreV1EphemeralVolumeSource(;readOnly=nothing, volumeClaimTemplate=nothing)
        o = new()
        validate_property(IoK8sApiCoreV1EphemeralVolumeSource, Symbol("readOnly"), readOnly)
        setfield!(o, Symbol("readOnly"), readOnly)
        validate_property(IoK8sApiCoreV1EphemeralVolumeSource, Symbol("volumeClaimTemplate"), volumeClaimTemplate)
        setfield!(o, Symbol("volumeClaimTemplate"), volumeClaimTemplate)
        o
    end
end # type IoK8sApiCoreV1EphemeralVolumeSource

const _property_map_IoK8sApiCoreV1EphemeralVolumeSource = Dict{Symbol,Symbol}(Symbol("readOnly")=>Symbol("readOnly"), Symbol("volumeClaimTemplate")=>Symbol("volumeClaimTemplate"))
const _property_types_IoK8sApiCoreV1EphemeralVolumeSource = Dict{Symbol,String}(Symbol("readOnly")=>"Bool", Symbol("volumeClaimTemplate")=>"IoK8sApiCoreV1PersistentVolumeClaimTemplate")
Base.propertynames(::Type{ IoK8sApiCoreV1EphemeralVolumeSource }) = collect(keys(_property_map_IoK8sApiCoreV1EphemeralVolumeSource))
Swagger.property_type(::Type{ IoK8sApiCoreV1EphemeralVolumeSource }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoK8sApiCoreV1EphemeralVolumeSource[name]))}
Swagger.field_name(::Type{ IoK8sApiCoreV1EphemeralVolumeSource }, property_name::Symbol) =  _property_map_IoK8sApiCoreV1EphemeralVolumeSource[property_name]

function check_required(o::IoK8sApiCoreV1EphemeralVolumeSource)
    true
end

function validate_property(::Type{ IoK8sApiCoreV1EphemeralVolumeSource }, name::Symbol, val)
end
