# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


@doc raw"""Provisioner is the Schema for the Provisioners API

    ShKarpenterV1alpha5Provisioner(;
        apiVersion=nothing,
        kind=nothing,
        metadata=nothing,
        spec=nothing,
        status=nothing,
    )

    - apiVersion::String : APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    - kind::String : Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    - metadata::IoK8sApimachineryPkgApisMetaV1ObjectMeta : Standard object&#39;s metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    - spec::ShKarpenterV1alpha5ProvisionerSpec
    - status::ShKarpenterV1alpha5ProvisionerStatus
"""
mutable struct ShKarpenterV1alpha5Provisioner <: SwaggerModel
    apiVersion::Any # spec type: Union{ Nothing, String } # spec name: apiVersion
    kind::Any # spec type: Union{ Nothing, String } # spec name: kind
    metadata::Any # spec type: Union{ Nothing, IoK8sApimachineryPkgApisMetaV1ObjectMeta } # spec name: metadata
    spec::Any # spec type: Union{ Nothing, ShKarpenterV1alpha5ProvisionerSpec } # spec name: spec
    status::Any # spec type: Union{ Nothing, ShKarpenterV1alpha5ProvisionerStatus } # spec name: status

    function ShKarpenterV1alpha5Provisioner(;apiVersion=nothing, kind=nothing, metadata=nothing, spec=nothing, status=nothing)
        o = new()
        validate_property(ShKarpenterV1alpha5Provisioner, Symbol("apiVersion"), apiVersion)
        setfield!(o, Symbol("apiVersion"), apiVersion)
        validate_property(ShKarpenterV1alpha5Provisioner, Symbol("kind"), kind)
        setfield!(o, Symbol("kind"), kind)
        validate_property(ShKarpenterV1alpha5Provisioner, Symbol("metadata"), metadata)
        setfield!(o, Symbol("metadata"), metadata)
        validate_property(ShKarpenterV1alpha5Provisioner, Symbol("spec"), spec)
        setfield!(o, Symbol("spec"), spec)
        validate_property(ShKarpenterV1alpha5Provisioner, Symbol("status"), status)
        setfield!(o, Symbol("status"), status)
        o
    end
end # type ShKarpenterV1alpha5Provisioner

const _property_map_ShKarpenterV1alpha5Provisioner = Dict{Symbol,Symbol}(Symbol("apiVersion")=>Symbol("apiVersion"), Symbol("kind")=>Symbol("kind"), Symbol("metadata")=>Symbol("metadata"), Symbol("spec")=>Symbol("spec"), Symbol("status")=>Symbol("status"))
const _property_types_ShKarpenterV1alpha5Provisioner = Dict{Symbol,String}(Symbol("apiVersion")=>"String", Symbol("kind")=>"String", Symbol("metadata")=>"IoK8sApimachineryPkgApisMetaV1ObjectMeta", Symbol("spec")=>"ShKarpenterV1alpha5ProvisionerSpec", Symbol("status")=>"ShKarpenterV1alpha5ProvisionerStatus")
Base.propertynames(::Type{ ShKarpenterV1alpha5Provisioner }) = collect(keys(_property_map_ShKarpenterV1alpha5Provisioner))
Swagger.property_type(::Type{ ShKarpenterV1alpha5Provisioner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ShKarpenterV1alpha5Provisioner[name]))}
Swagger.field_name(::Type{ ShKarpenterV1alpha5Provisioner }, property_name::Symbol) =  _property_map_ShKarpenterV1alpha5Provisioner[property_name]

function check_required(o::ShKarpenterV1alpha5Provisioner)
    true
end

function validate_property(::Type{ ShKarpenterV1alpha5Provisioner }, name::Symbol, val)
end
