# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


@doc raw"""HPAScalingPolicy is a single policy which must hold true for a specified past interval.

    IoK8sApiAutoscalingV2beta2HPAScalingPolicy(;
        periodSeconds=nothing,
        type=nothing,
        value=nothing,
    )

    - periodSeconds::Int32 : PeriodSeconds specifies the window of time for which the policy should hold true. PeriodSeconds must be greater than zero and less than or equal to 1800 (30 min).
    - type::String : Type is used to specify the scaling policy.
    - value::Int32 : Value contains the amount of change which is permitted by the policy. It must be greater than zero
"""
mutable struct IoK8sApiAutoscalingV2beta2HPAScalingPolicy <: SwaggerModel
    periodSeconds::Any # spec type: Union{ Nothing, Int32 } # spec name: periodSeconds
    type::Any # spec type: Union{ Nothing, String } # spec name: type
    value::Any # spec type: Union{ Nothing, Int32 } # spec name: value

    function IoK8sApiAutoscalingV2beta2HPAScalingPolicy(;periodSeconds=nothing, type=nothing, value=nothing)
        o = new()
        validate_property(IoK8sApiAutoscalingV2beta2HPAScalingPolicy, Symbol("periodSeconds"), periodSeconds)
        setfield!(o, Symbol("periodSeconds"), periodSeconds)
        validate_property(IoK8sApiAutoscalingV2beta2HPAScalingPolicy, Symbol("type"), type)
        setfield!(o, Symbol("type"), type)
        validate_property(IoK8sApiAutoscalingV2beta2HPAScalingPolicy, Symbol("value"), value)
        setfield!(o, Symbol("value"), value)
        o
    end
end # type IoK8sApiAutoscalingV2beta2HPAScalingPolicy

const _property_map_IoK8sApiAutoscalingV2beta2HPAScalingPolicy = Dict{Symbol,Symbol}(Symbol("periodSeconds")=>Symbol("periodSeconds"), Symbol("type")=>Symbol("type"), Symbol("value")=>Symbol("value"))
const _property_types_IoK8sApiAutoscalingV2beta2HPAScalingPolicy = Dict{Symbol,String}(Symbol("periodSeconds")=>"Int32", Symbol("type")=>"String", Symbol("value")=>"Int32")
Base.propertynames(::Type{ IoK8sApiAutoscalingV2beta2HPAScalingPolicy }) = collect(keys(_property_map_IoK8sApiAutoscalingV2beta2HPAScalingPolicy))
Swagger.property_type(::Type{ IoK8sApiAutoscalingV2beta2HPAScalingPolicy }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoK8sApiAutoscalingV2beta2HPAScalingPolicy[name]))}
Swagger.field_name(::Type{ IoK8sApiAutoscalingV2beta2HPAScalingPolicy }, property_name::Symbol) =  _property_map_IoK8sApiAutoscalingV2beta2HPAScalingPolicy[property_name]

function check_required(o::IoK8sApiAutoscalingV2beta2HPAScalingPolicy)
    (getproperty(o, Symbol("periodSeconds")) === nothing) && (return false)
    (getproperty(o, Symbol("type")) === nothing) && (return false)
    (getproperty(o, Symbol("value")) === nothing) && (return false)
    true
end

function validate_property(::Type{ IoK8sApiAutoscalingV2beta2HPAScalingPolicy }, name::Symbol, val)
end
