# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


@doc raw"""UserSubject holds detailed information for user-kind subject.

    IoK8sApiFlowcontrolV1beta1UserSubject(;
        name=nothing,
    )

    - name::String : &#x60;name&#x60; is the username that matches, or \&quot;*\&quot; to match all usernames. Required.
"""
mutable struct IoK8sApiFlowcontrolV1beta1UserSubject <: SwaggerModel
    name::Any # spec type: Union{ Nothing, String } # spec name: name

    function IoK8sApiFlowcontrolV1beta1UserSubject(;name=nothing)
        o = new()
        validate_property(IoK8sApiFlowcontrolV1beta1UserSubject, Symbol("name"), name)
        setfield!(o, Symbol("name"), name)
        o
    end
end # type IoK8sApiFlowcontrolV1beta1UserSubject

const _property_map_IoK8sApiFlowcontrolV1beta1UserSubject = Dict{Symbol,Symbol}(Symbol("name")=>Symbol("name"))
const _property_types_IoK8sApiFlowcontrolV1beta1UserSubject = Dict{Symbol,String}(Symbol("name")=>"String")
Base.propertynames(::Type{ IoK8sApiFlowcontrolV1beta1UserSubject }) = collect(keys(_property_map_IoK8sApiFlowcontrolV1beta1UserSubject))
Swagger.property_type(::Type{ IoK8sApiFlowcontrolV1beta1UserSubject }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoK8sApiFlowcontrolV1beta1UserSubject[name]))}
Swagger.field_name(::Type{ IoK8sApiFlowcontrolV1beta1UserSubject }, property_name::Symbol) =  _property_map_IoK8sApiFlowcontrolV1beta1UserSubject[property_name]

function check_required(o::IoK8sApiFlowcontrolV1beta1UserSubject)
    (getproperty(o, Symbol("name")) === nothing) && (return false)
    true
end

function validate_property(::Type{ IoK8sApiFlowcontrolV1beta1UserSubject }, name::Symbol, val)
end
