# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


@doc raw"""
    OrgProjectcalicoCrdV1ClusterInformation(;
    )

"""
mutable struct OrgProjectcalicoCrdV1ClusterInformation <: SwaggerModel

    function OrgProjectcalicoCrdV1ClusterInformation(;)
        o = new()
        o
    end
end # type OrgProjectcalicoCrdV1ClusterInformation

const _property_map_OrgProjectcalicoCrdV1ClusterInformation = Dict{Symbol,Symbol}()
const _property_types_OrgProjectcalicoCrdV1ClusterInformation = Dict{Symbol,String}()
Base.propertynames(::Type{ OrgProjectcalicoCrdV1ClusterInformation }) = collect(keys(_property_map_OrgProjectcalicoCrdV1ClusterInformation))
Swagger.property_type(::Type{ OrgProjectcalicoCrdV1ClusterInformation }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_OrgProjectcalicoCrdV1ClusterInformation[name]))}
Swagger.field_name(::Type{ OrgProjectcalicoCrdV1ClusterInformation }, property_name::Symbol) =  _property_map_OrgProjectcalicoCrdV1ClusterInformation[property_name]

function check_required(o::OrgProjectcalicoCrdV1ClusterInformation)
    true
end

function validate_property(::Type{ OrgProjectcalicoCrdV1ClusterInformation }, name::Symbol, val)
end
