# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


@doc raw"""
    OrgProjectcalicoCrdV1HostEndpoint(;
    )

"""
mutable struct OrgProjectcalicoCrdV1HostEndpoint <: SwaggerModel

    function OrgProjectcalicoCrdV1HostEndpoint(;)
        o = new()
        o
    end
end # type OrgProjectcalicoCrdV1HostEndpoint

const _property_map_OrgProjectcalicoCrdV1HostEndpoint = Dict{Symbol,Symbol}()
const _property_types_OrgProjectcalicoCrdV1HostEndpoint = Dict{Symbol,String}()
Base.propertynames(::Type{ OrgProjectcalicoCrdV1HostEndpoint }) = collect(keys(_property_map_OrgProjectcalicoCrdV1HostEndpoint))
Swagger.property_type(::Type{ OrgProjectcalicoCrdV1HostEndpoint }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_OrgProjectcalicoCrdV1HostEndpoint[name]))}
Swagger.field_name(::Type{ OrgProjectcalicoCrdV1HostEndpoint }, property_name::Symbol) =  _property_map_OrgProjectcalicoCrdV1HostEndpoint[property_name]

function check_required(o::OrgProjectcalicoCrdV1HostEndpoint)
    true
end

function validate_property(::Type{ OrgProjectcalicoCrdV1HostEndpoint }, name::Symbol, val)
end
