# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


@doc raw"""ServiceBackendPort is the service port being referenced.

    IoK8sApiNetworkingV1ServiceBackendPort(;
        name=nothing,
        number=nothing,
    )

    - name::String : Name is the name of the port on the Service. This is a mutually exclusive setting with \&quot;Number\&quot;.
    - number::Int32 : Number is the numerical port number (e.g. 80) on the Service. This is a mutually exclusive setting with \&quot;Name\&quot;.
"""
mutable struct IoK8sApiNetworkingV1ServiceBackendPort <: SwaggerModel
    name::Any # spec type: Union{ Nothing, String } # spec name: name
    number::Any # spec type: Union{ Nothing, Int32 } # spec name: number

    function IoK8sApiNetworkingV1ServiceBackendPort(;name=nothing, number=nothing)
        o = new()
        validate_property(IoK8sApiNetworkingV1ServiceBackendPort, Symbol("name"), name)
        setfield!(o, Symbol("name"), name)
        validate_property(IoK8sApiNetworkingV1ServiceBackendPort, Symbol("number"), number)
        setfield!(o, Symbol("number"), number)
        o
    end
end # type IoK8sApiNetworkingV1ServiceBackendPort

const _property_map_IoK8sApiNetworkingV1ServiceBackendPort = Dict{Symbol,Symbol}(Symbol("name")=>Symbol("name"), Symbol("number")=>Symbol("number"))
const _property_types_IoK8sApiNetworkingV1ServiceBackendPort = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("number")=>"Int32")
Base.propertynames(::Type{ IoK8sApiNetworkingV1ServiceBackendPort }) = collect(keys(_property_map_IoK8sApiNetworkingV1ServiceBackendPort))
Swagger.property_type(::Type{ IoK8sApiNetworkingV1ServiceBackendPort }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoK8sApiNetworkingV1ServiceBackendPort[name]))}
Swagger.field_name(::Type{ IoK8sApiNetworkingV1ServiceBackendPort }, property_name::Symbol) =  _property_map_IoK8sApiNetworkingV1ServiceBackendPort[property_name]

function check_required(o::IoK8sApiNetworkingV1ServiceBackendPort)
    true
end

function validate_property(::Type{ IoK8sApiNetworkingV1ServiceBackendPort }, name::Symbol, val)
end
