# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


@doc raw"""
    OrgProjectcalicoCrdV1IPPool(;
    )

"""
mutable struct OrgProjectcalicoCrdV1IPPool <: SwaggerModel

    function OrgProjectcalicoCrdV1IPPool(;)
        o = new()
        o
    end
end # type OrgProjectcalicoCrdV1IPPool

const _property_map_OrgProjectcalicoCrdV1IPPool = Dict{Symbol,Symbol}()
const _property_types_OrgProjectcalicoCrdV1IPPool = Dict{Symbol,String}()
Base.propertynames(::Type{ OrgProjectcalicoCrdV1IPPool }) = collect(keys(_property_map_OrgProjectcalicoCrdV1IPPool))
Swagger.property_type(::Type{ OrgProjectcalicoCrdV1IPPool }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_OrgProjectcalicoCrdV1IPPool[name]))}
Swagger.field_name(::Type{ OrgProjectcalicoCrdV1IPPool }, property_name::Symbol) =  _property_map_OrgProjectcalicoCrdV1IPPool[property_name]

function check_required(o::OrgProjectcalicoCrdV1IPPool)
    true
end

function validate_property(::Type{ OrgProjectcalicoCrdV1IPPool }, name::Symbol, val)
end
