# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


@doc raw"""
    OrgProjectcalicoCrdV1GlobalNetworkSet(;
    )

"""
mutable struct OrgProjectcalicoCrdV1GlobalNetworkSet <: SwaggerModel

    function OrgProjectcalicoCrdV1GlobalNetworkSet(;)
        o = new()
        o
    end
end # type OrgProjectcalicoCrdV1GlobalNetworkSet

const _property_map_OrgProjectcalicoCrdV1GlobalNetworkSet = Dict{Symbol,Symbol}()
const _property_types_OrgProjectcalicoCrdV1GlobalNetworkSet = Dict{Symbol,String}()
Base.propertynames(::Type{ OrgProjectcalicoCrdV1GlobalNetworkSet }) = collect(keys(_property_map_OrgProjectcalicoCrdV1GlobalNetworkSet))
Swagger.property_type(::Type{ OrgProjectcalicoCrdV1GlobalNetworkSet }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_OrgProjectcalicoCrdV1GlobalNetworkSet[name]))}
Swagger.field_name(::Type{ OrgProjectcalicoCrdV1GlobalNetworkSet }, property_name::Symbol) =  _property_map_OrgProjectcalicoCrdV1GlobalNetworkSet[property_name]

function check_required(o::OrgProjectcalicoCrdV1GlobalNetworkSet)
    true
end

function validate_property(::Type{ OrgProjectcalicoCrdV1GlobalNetworkSet }, name::Symbol, val)
end
