# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


@doc raw"""A node selector requirement is a selector that contains values, a key, and an operator that relates the key and values.

    ShKarpenterV1alpha5ProvisionerSpecRequirements(;
        key=nothing,
        operator=nothing,
        values=nothing,
    )

    - key::String : The label key that the selector applies to.
    - operator::String : Represents a key&#39;s relationship to a set of values. Valid operators are In, NotIn, Exists, DoesNotExist. Gt, and Lt.
    - values::Vector{String} : An array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. If the operator is Gt or Lt, the values array must have a single element, which will be interpreted as an integer. This array is replaced during a strategic merge patch.
"""
mutable struct ShKarpenterV1alpha5ProvisionerSpecRequirements <: SwaggerModel
    key::Any # spec type: Union{ Nothing, String } # spec name: key
    operator::Any # spec type: Union{ Nothing, String } # spec name: operator
    values::Any # spec type: Union{ Nothing, Vector{String} } # spec name: values

    function ShKarpenterV1alpha5ProvisionerSpecRequirements(;key=nothing, operator=nothing, values=nothing)
        o = new()
        validate_property(ShKarpenterV1alpha5ProvisionerSpecRequirements, Symbol("key"), key)
        setfield!(o, Symbol("key"), key)
        validate_property(ShKarpenterV1alpha5ProvisionerSpecRequirements, Symbol("operator"), operator)
        setfield!(o, Symbol("operator"), operator)
        validate_property(ShKarpenterV1alpha5ProvisionerSpecRequirements, Symbol("values"), values)
        setfield!(o, Symbol("values"), values)
        o
    end
end # type ShKarpenterV1alpha5ProvisionerSpecRequirements

const _property_map_ShKarpenterV1alpha5ProvisionerSpecRequirements = Dict{Symbol,Symbol}(Symbol("key")=>Symbol("key"), Symbol("operator")=>Symbol("operator"), Symbol("values")=>Symbol("values"))
const _property_types_ShKarpenterV1alpha5ProvisionerSpecRequirements = Dict{Symbol,String}(Symbol("key")=>"String", Symbol("operator")=>"String", Symbol("values")=>"Vector{String}")
Base.propertynames(::Type{ ShKarpenterV1alpha5ProvisionerSpecRequirements }) = collect(keys(_property_map_ShKarpenterV1alpha5ProvisionerSpecRequirements))
Swagger.property_type(::Type{ ShKarpenterV1alpha5ProvisionerSpecRequirements }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ShKarpenterV1alpha5ProvisionerSpecRequirements[name]))}
Swagger.field_name(::Type{ ShKarpenterV1alpha5ProvisionerSpecRequirements }, property_name::Symbol) =  _property_map_ShKarpenterV1alpha5ProvisionerSpecRequirements[property_name]

function check_required(o::ShKarpenterV1alpha5ProvisionerSpecRequirements)
    (getproperty(o, Symbol("key")) === nothing) && (return false)
    (getproperty(o, Symbol("operator")) === nothing) && (return false)
    true
end

function validate_property(::Type{ ShKarpenterV1alpha5ProvisionerSpecRequirements }, name::Symbol, val)
end
