# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


@doc raw"""ClusterInformationList is a list of ClusterInformation

    OrgProjectcalicoCrdV1ClusterInformationList(;
        apiVersion=nothing,
        items=nothing,
        kind=nothing,
        metadata=nothing,
    )

    - apiVersion::String : APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    - items::Vector{OrgProjectcalicoCrdV1ClusterInformation} : List of clusterinformations. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    - kind::String : Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    - metadata::IoK8sApimachineryPkgApisMetaV1ListMeta : Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
"""
mutable struct OrgProjectcalicoCrdV1ClusterInformationList <: SwaggerModel
    apiVersion::Any # spec type: Union{ Nothing, String } # spec name: apiVersion
    items::Any # spec type: Union{ Nothing, Vector{OrgProjectcalicoCrdV1ClusterInformation} } # spec name: items
    kind::Any # spec type: Union{ Nothing, String } # spec name: kind
    metadata::Any # spec type: Union{ Nothing, IoK8sApimachineryPkgApisMetaV1ListMeta } # spec name: metadata

    function OrgProjectcalicoCrdV1ClusterInformationList(;apiVersion=nothing, items=nothing, kind=nothing, metadata=nothing)
        o = new()
        validate_property(OrgProjectcalicoCrdV1ClusterInformationList, Symbol("apiVersion"), apiVersion)
        setfield!(o, Symbol("apiVersion"), apiVersion)
        validate_property(OrgProjectcalicoCrdV1ClusterInformationList, Symbol("items"), items)
        setfield!(o, Symbol("items"), items)
        validate_property(OrgProjectcalicoCrdV1ClusterInformationList, Symbol("kind"), kind)
        setfield!(o, Symbol("kind"), kind)
        validate_property(OrgProjectcalicoCrdV1ClusterInformationList, Symbol("metadata"), metadata)
        setfield!(o, Symbol("metadata"), metadata)
        o
    end
end # type OrgProjectcalicoCrdV1ClusterInformationList

const _property_map_OrgProjectcalicoCrdV1ClusterInformationList = Dict{Symbol,Symbol}(Symbol("apiVersion")=>Symbol("apiVersion"), Symbol("items")=>Symbol("items"), Symbol("kind")=>Symbol("kind"), Symbol("metadata")=>Symbol("metadata"))
const _property_types_OrgProjectcalicoCrdV1ClusterInformationList = Dict{Symbol,String}(Symbol("apiVersion")=>"String", Symbol("items")=>"Vector{OrgProjectcalicoCrdV1ClusterInformation}", Symbol("kind")=>"String", Symbol("metadata")=>"IoK8sApimachineryPkgApisMetaV1ListMeta")
Base.propertynames(::Type{ OrgProjectcalicoCrdV1ClusterInformationList }) = collect(keys(_property_map_OrgProjectcalicoCrdV1ClusterInformationList))
Swagger.property_type(::Type{ OrgProjectcalicoCrdV1ClusterInformationList }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_OrgProjectcalicoCrdV1ClusterInformationList[name]))}
Swagger.field_name(::Type{ OrgProjectcalicoCrdV1ClusterInformationList }, property_name::Symbol) =  _property_map_OrgProjectcalicoCrdV1ClusterInformationList[property_name]

function check_required(o::OrgProjectcalicoCrdV1ClusterInformationList)
    (getproperty(o, Symbol("items")) === nothing) && (return false)
    true
end

function validate_property(::Type{ OrgProjectcalicoCrdV1ClusterInformationList }, name::Symbol, val)
end
