# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


@doc raw"""
    OrgProjectcalicoCrdV1IPAMBlock(;
    )

"""
mutable struct OrgProjectcalicoCrdV1IPAMBlock <: SwaggerModel

    function OrgProjectcalicoCrdV1IPAMBlock(;)
        o = new()
        o
    end
end # type OrgProjectcalicoCrdV1IPAMBlock

const _property_map_OrgProjectcalicoCrdV1IPAMBlock = Dict{Symbol,Symbol}()
const _property_types_OrgProjectcalicoCrdV1IPAMBlock = Dict{Symbol,String}()
Base.propertynames(::Type{ OrgProjectcalicoCrdV1IPAMBlock }) = collect(keys(_property_map_OrgProjectcalicoCrdV1IPAMBlock))
Swagger.property_type(::Type{ OrgProjectcalicoCrdV1IPAMBlock }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_OrgProjectcalicoCrdV1IPAMBlock[name]))}
Swagger.field_name(::Type{ OrgProjectcalicoCrdV1IPAMBlock }, property_name::Symbol) =  _property_map_OrgProjectcalicoCrdV1IPAMBlock[property_name]

function check_required(o::OrgProjectcalicoCrdV1IPAMBlock)
    true
end

function validate_property(::Type{ OrgProjectcalicoCrdV1IPAMBlock }, name::Symbol, val)
end
