# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


@doc raw"""ProvisionerList is a list of Provisioner

    ShKarpenterV1alpha5ProvisionerList(;
        apiVersion=nothing,
        items=nothing,
        kind=nothing,
        metadata=nothing,
    )

    - apiVersion::String : APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    - items::Vector{ShKarpenterV1alpha5Provisioner} : List of provisioners. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    - kind::String : Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    - metadata::IoK8sApimachineryPkgApisMetaV1ListMeta : Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
"""
mutable struct ShKarpenterV1alpha5ProvisionerList <: SwaggerModel
    apiVersion::Any # spec type: Union{ Nothing, String } # spec name: apiVersion
    items::Any # spec type: Union{ Nothing, Vector{ShKarpenterV1alpha5Provisioner} } # spec name: items
    kind::Any # spec type: Union{ Nothing, String } # spec name: kind
    metadata::Any # spec type: Union{ Nothing, IoK8sApimachineryPkgApisMetaV1ListMeta } # spec name: metadata

    function ShKarpenterV1alpha5ProvisionerList(;apiVersion=nothing, items=nothing, kind=nothing, metadata=nothing)
        o = new()
        validate_property(ShKarpenterV1alpha5ProvisionerList, Symbol("apiVersion"), apiVersion)
        setfield!(o, Symbol("apiVersion"), apiVersion)
        validate_property(ShKarpenterV1alpha5ProvisionerList, Symbol("items"), items)
        setfield!(o, Symbol("items"), items)
        validate_property(ShKarpenterV1alpha5ProvisionerList, Symbol("kind"), kind)
        setfield!(o, Symbol("kind"), kind)
        validate_property(ShKarpenterV1alpha5ProvisionerList, Symbol("metadata"), metadata)
        setfield!(o, Symbol("metadata"), metadata)
        o
    end
end # type ShKarpenterV1alpha5ProvisionerList

const _property_map_ShKarpenterV1alpha5ProvisionerList = Dict{Symbol,Symbol}(Symbol("apiVersion")=>Symbol("apiVersion"), Symbol("items")=>Symbol("items"), Symbol("kind")=>Symbol("kind"), Symbol("metadata")=>Symbol("metadata"))
const _property_types_ShKarpenterV1alpha5ProvisionerList = Dict{Symbol,String}(Symbol("apiVersion")=>"String", Symbol("items")=>"Vector{ShKarpenterV1alpha5Provisioner}", Symbol("kind")=>"String", Symbol("metadata")=>"IoK8sApimachineryPkgApisMetaV1ListMeta")
Base.propertynames(::Type{ ShKarpenterV1alpha5ProvisionerList }) = collect(keys(_property_map_ShKarpenterV1alpha5ProvisionerList))
Swagger.property_type(::Type{ ShKarpenterV1alpha5ProvisionerList }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ShKarpenterV1alpha5ProvisionerList[name]))}
Swagger.field_name(::Type{ ShKarpenterV1alpha5ProvisionerList }, property_name::Symbol) =  _property_map_ShKarpenterV1alpha5ProvisionerList[property_name]

function check_required(o::ShKarpenterV1alpha5ProvisionerList)
    (getproperty(o, Symbol("items")) === nothing) && (return false)
    true
end

function validate_property(::Type{ ShKarpenterV1alpha5ProvisionerList }, name::Symbol, val)
end
