# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


@doc raw"""
    OrgProjectcalicoCrdV1BlockAffinity(;
    )

"""
mutable struct OrgProjectcalicoCrdV1BlockAffinity <: SwaggerModel

    function OrgProjectcalicoCrdV1BlockAffinity(;)
        o = new()
        o
    end
end # type OrgProjectcalicoCrdV1BlockAffinity

const _property_map_OrgProjectcalicoCrdV1BlockAffinity = Dict{Symbol,Symbol}()
const _property_types_OrgProjectcalicoCrdV1BlockAffinity = Dict{Symbol,String}()
Base.propertynames(::Type{ OrgProjectcalicoCrdV1BlockAffinity }) = collect(keys(_property_map_OrgProjectcalicoCrdV1BlockAffinity))
Swagger.property_type(::Type{ OrgProjectcalicoCrdV1BlockAffinity }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_OrgProjectcalicoCrdV1BlockAffinity[name]))}
Swagger.field_name(::Type{ OrgProjectcalicoCrdV1BlockAffinity }, property_name::Symbol) =  _property_map_OrgProjectcalicoCrdV1BlockAffinity[property_name]

function check_required(o::OrgProjectcalicoCrdV1BlockAffinity)
    true
end

function validate_property(::Type{ OrgProjectcalicoCrdV1BlockAffinity }, name::Symbol, val)
end
