# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


@doc raw"""ContainerResourceMetricSource indicates how to scale on a resource metric known to Kubernetes, as specified in requests and limits, describing each pod in the current scale target (e.g. CPU or memory).  The values will be averaged together before being compared to the target.  Such metrics are built in to Kubernetes, and have special scaling options on top of those available to normal per-pod metrics using the \&quot;pods\&quot; source.  Only one \&quot;target\&quot; type should be set.

    IoK8sApiAutoscalingV2beta2ContainerResourceMetricSource(;
        container=nothing,
        name=nothing,
        target=nothing,
    )

    - container::String : container is the name of the container in the pods of the scaling target
    - name::String : name is the name of the resource in question.
    - target::IoK8sApiAutoscalingV2beta2MetricTarget : target specifies the target value for the given metric
"""
mutable struct IoK8sApiAutoscalingV2beta2ContainerResourceMetricSource <: SwaggerModel
    container::Any # spec type: Union{ Nothing, String } # spec name: container
    name::Any # spec type: Union{ Nothing, String } # spec name: name
    target::Any # spec type: Union{ Nothing, IoK8sApiAutoscalingV2beta2MetricTarget } # spec name: target

    function IoK8sApiAutoscalingV2beta2ContainerResourceMetricSource(;container=nothing, name=nothing, target=nothing)
        o = new()
        validate_property(IoK8sApiAutoscalingV2beta2ContainerResourceMetricSource, Symbol("container"), container)
        setfield!(o, Symbol("container"), container)
        validate_property(IoK8sApiAutoscalingV2beta2ContainerResourceMetricSource, Symbol("name"), name)
        setfield!(o, Symbol("name"), name)
        validate_property(IoK8sApiAutoscalingV2beta2ContainerResourceMetricSource, Symbol("target"), target)
        setfield!(o, Symbol("target"), target)
        o
    end
end # type IoK8sApiAutoscalingV2beta2ContainerResourceMetricSource

const _property_map_IoK8sApiAutoscalingV2beta2ContainerResourceMetricSource = Dict{Symbol,Symbol}(Symbol("container")=>Symbol("container"), Symbol("name")=>Symbol("name"), Symbol("target")=>Symbol("target"))
const _property_types_IoK8sApiAutoscalingV2beta2ContainerResourceMetricSource = Dict{Symbol,String}(Symbol("container")=>"String", Symbol("name")=>"String", Symbol("target")=>"IoK8sApiAutoscalingV2beta2MetricTarget")
Base.propertynames(::Type{ IoK8sApiAutoscalingV2beta2ContainerResourceMetricSource }) = collect(keys(_property_map_IoK8sApiAutoscalingV2beta2ContainerResourceMetricSource))
Swagger.property_type(::Type{ IoK8sApiAutoscalingV2beta2ContainerResourceMetricSource }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoK8sApiAutoscalingV2beta2ContainerResourceMetricSource[name]))}
Swagger.field_name(::Type{ IoK8sApiAutoscalingV2beta2ContainerResourceMetricSource }, property_name::Symbol) =  _property_map_IoK8sApiAutoscalingV2beta2ContainerResourceMetricSource[property_name]

function check_required(o::IoK8sApiAutoscalingV2beta2ContainerResourceMetricSource)
    (getproperty(o, Symbol("container")) === nothing) && (return false)
    (getproperty(o, Symbol("name")) === nothing) && (return false)
    (getproperty(o, Symbol("target")) === nothing) && (return false)
    true
end

function validate_property(::Type{ IoK8sApiAutoscalingV2beta2ContainerResourceMetricSource }, name::Symbol, val)
end
