# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


@doc raw"""
    ComAmazonawsK8sCrdV1alpha1ENIConfig(;
    )

"""
mutable struct ComAmazonawsK8sCrdV1alpha1ENIConfig <: SwaggerModel

    function ComAmazonawsK8sCrdV1alpha1ENIConfig(;)
        o = new()
        o
    end
end # type ComAmazonawsK8sCrdV1alpha1ENIConfig

const _property_map_ComAmazonawsK8sCrdV1alpha1ENIConfig = Dict{Symbol,Symbol}()
const _property_types_ComAmazonawsK8sCrdV1alpha1ENIConfig = Dict{Symbol,String}()
Base.propertynames(::Type{ ComAmazonawsK8sCrdV1alpha1ENIConfig }) = collect(keys(_property_map_ComAmazonawsK8sCrdV1alpha1ENIConfig))
Swagger.property_type(::Type{ ComAmazonawsK8sCrdV1alpha1ENIConfig }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ComAmazonawsK8sCrdV1alpha1ENIConfig[name]))}
Swagger.field_name(::Type{ ComAmazonawsK8sCrdV1alpha1ENIConfig }, property_name::Symbol) =  _property_map_ComAmazonawsK8sCrdV1alpha1ENIConfig[property_name]

function check_required(o::ComAmazonawsK8sCrdV1alpha1ENIConfig)
    true
end

function validate_property(::Type{ ComAmazonawsK8sCrdV1alpha1ENIConfig }, name::Symbol, val)
end
