# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


@doc raw"""
    OrgProjectcalicoCrdV1FelixConfiguration(;
    )

"""
mutable struct OrgProjectcalicoCrdV1FelixConfiguration <: SwaggerModel

    function OrgProjectcalicoCrdV1FelixConfiguration(;)
        o = new()
        o
    end
end # type OrgProjectcalicoCrdV1FelixConfiguration

const _property_map_OrgProjectcalicoCrdV1FelixConfiguration = Dict{Symbol,Symbol}()
const _property_types_OrgProjectcalicoCrdV1FelixConfiguration = Dict{Symbol,String}()
Base.propertynames(::Type{ OrgProjectcalicoCrdV1FelixConfiguration }) = collect(keys(_property_map_OrgProjectcalicoCrdV1FelixConfiguration))
Swagger.property_type(::Type{ OrgProjectcalicoCrdV1FelixConfiguration }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_OrgProjectcalicoCrdV1FelixConfiguration[name]))}
Swagger.field_name(::Type{ OrgProjectcalicoCrdV1FelixConfiguration }, property_name::Symbol) =  _property_map_OrgProjectcalicoCrdV1FelixConfiguration[property_name]

function check_required(o::OrgProjectcalicoCrdV1FelixConfiguration)
    true
end

function validate_property(::Type{ OrgProjectcalicoCrdV1FelixConfiguration }, name::Symbol, val)
end
