# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


@doc raw"""
    AwsK8sVpcresourcesV1beta1SecurityGroupPolicy(;
    )

"""
mutable struct AwsK8sVpcresourcesV1beta1SecurityGroupPolicy <: SwaggerModel

    function AwsK8sVpcresourcesV1beta1SecurityGroupPolicy(;)
        o = new()
        o
    end
end # type AwsK8sVpcresourcesV1beta1SecurityGroupPolicy

const _property_map_AwsK8sVpcresourcesV1beta1SecurityGroupPolicy = Dict{Symbol,Symbol}()
const _property_types_AwsK8sVpcresourcesV1beta1SecurityGroupPolicy = Dict{Symbol,String}()
Base.propertynames(::Type{ AwsK8sVpcresourcesV1beta1SecurityGroupPolicy }) = collect(keys(_property_map_AwsK8sVpcresourcesV1beta1SecurityGroupPolicy))
Swagger.property_type(::Type{ AwsK8sVpcresourcesV1beta1SecurityGroupPolicy }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AwsK8sVpcresourcesV1beta1SecurityGroupPolicy[name]))}
Swagger.field_name(::Type{ AwsK8sVpcresourcesV1beta1SecurityGroupPolicy }, property_name::Symbol) =  _property_map_AwsK8sVpcresourcesV1beta1SecurityGroupPolicy[property_name]

function check_required(o::AwsK8sVpcresourcesV1beta1SecurityGroupPolicy)
    true
end

function validate_property(::Type{ AwsK8sVpcresourcesV1beta1SecurityGroupPolicy }, name::Symbol, val)
end
