# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


@doc raw"""
    OrgProjectcalicoCrdV1BGPPeer(;
    )

"""
mutable struct OrgProjectcalicoCrdV1BGPPeer <: SwaggerModel

    function OrgProjectcalicoCrdV1BGPPeer(;)
        o = new()
        o
    end
end # type OrgProjectcalicoCrdV1BGPPeer

const _property_map_OrgProjectcalicoCrdV1BGPPeer = Dict{Symbol,Symbol}()
const _property_types_OrgProjectcalicoCrdV1BGPPeer = Dict{Symbol,String}()
Base.propertynames(::Type{ OrgProjectcalicoCrdV1BGPPeer }) = collect(keys(_property_map_OrgProjectcalicoCrdV1BGPPeer))
Swagger.property_type(::Type{ OrgProjectcalicoCrdV1BGPPeer }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_OrgProjectcalicoCrdV1BGPPeer[name]))}
Swagger.field_name(::Type{ OrgProjectcalicoCrdV1BGPPeer }, property_name::Symbol) =  _property_map_OrgProjectcalicoCrdV1BGPPeer[property_name]

function check_required(o::OrgProjectcalicoCrdV1BGPPeer)
    true
end

function validate_property(::Type{ OrgProjectcalicoCrdV1BGPPeer }, name::Symbol, val)
end
