# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


@doc raw"""ENIConfigList is a list of ENIConfig

    ComAmazonawsK8sCrdV1alpha1ENIConfigList(;
        apiVersion=nothing,
        items=nothing,
        kind=nothing,
        metadata=nothing,
    )

    - apiVersion::String : APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    - items::Vector{ComAmazonawsK8sCrdV1alpha1ENIConfig} : List of eniconfigs. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    - kind::String : Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    - metadata::IoK8sApimachineryPkgApisMetaV1ListMeta : Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
"""
mutable struct ComAmazonawsK8sCrdV1alpha1ENIConfigList <: SwaggerModel
    apiVersion::Any # spec type: Union{ Nothing, String } # spec name: apiVersion
    items::Any # spec type: Union{ Nothing, Vector{ComAmazonawsK8sCrdV1alpha1ENIConfig} } # spec name: items
    kind::Any # spec type: Union{ Nothing, String } # spec name: kind
    metadata::Any # spec type: Union{ Nothing, IoK8sApimachineryPkgApisMetaV1ListMeta } # spec name: metadata

    function ComAmazonawsK8sCrdV1alpha1ENIConfigList(;apiVersion=nothing, items=nothing, kind=nothing, metadata=nothing)
        o = new()
        validate_property(ComAmazonawsK8sCrdV1alpha1ENIConfigList, Symbol("apiVersion"), apiVersion)
        setfield!(o, Symbol("apiVersion"), apiVersion)
        validate_property(ComAmazonawsK8sCrdV1alpha1ENIConfigList, Symbol("items"), items)
        setfield!(o, Symbol("items"), items)
        validate_property(ComAmazonawsK8sCrdV1alpha1ENIConfigList, Symbol("kind"), kind)
        setfield!(o, Symbol("kind"), kind)
        validate_property(ComAmazonawsK8sCrdV1alpha1ENIConfigList, Symbol("metadata"), metadata)
        setfield!(o, Symbol("metadata"), metadata)
        o
    end
end # type ComAmazonawsK8sCrdV1alpha1ENIConfigList

const _property_map_ComAmazonawsK8sCrdV1alpha1ENIConfigList = Dict{Symbol,Symbol}(Symbol("apiVersion")=>Symbol("apiVersion"), Symbol("items")=>Symbol("items"), Symbol("kind")=>Symbol("kind"), Symbol("metadata")=>Symbol("metadata"))
const _property_types_ComAmazonawsK8sCrdV1alpha1ENIConfigList = Dict{Symbol,String}(Symbol("apiVersion")=>"String", Symbol("items")=>"Vector{ComAmazonawsK8sCrdV1alpha1ENIConfig}", Symbol("kind")=>"String", Symbol("metadata")=>"IoK8sApimachineryPkgApisMetaV1ListMeta")
Base.propertynames(::Type{ ComAmazonawsK8sCrdV1alpha1ENIConfigList }) = collect(keys(_property_map_ComAmazonawsK8sCrdV1alpha1ENIConfigList))
Swagger.property_type(::Type{ ComAmazonawsK8sCrdV1alpha1ENIConfigList }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ComAmazonawsK8sCrdV1alpha1ENIConfigList[name]))}
Swagger.field_name(::Type{ ComAmazonawsK8sCrdV1alpha1ENIConfigList }, property_name::Symbol) =  _property_map_ComAmazonawsK8sCrdV1alpha1ENIConfigList[property_name]

function check_required(o::ComAmazonawsK8sCrdV1alpha1ENIConfigList)
    (getproperty(o, Symbol("items")) === nothing) && (return false)
    true
end

function validate_property(::Type{ ComAmazonawsK8sCrdV1alpha1ENIConfigList }, name::Symbol, val)
end
